### ISSUE TITLE
[BUG] Attempted import error: 'useActionState' is not exported from 'react' (imported as 'React')

### ISSUE THREAD

**Issue by tuankietcoderr** [TheEdoRan/next-safe-action#122]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

Hello it's me again! I'm building next project and this error occured:

![Screenshot 2024-05-11 at 05 52 32](https://github.com/TheEdoRan/next-safe-action/assets/84491737/48027b0e-d745-43eb-9110-cb64e4287ae0)

I'd tried to import React to my main code but it still be like that
![Screenshot 2024-05-11 at 05 53 05](https://github.com/TheEdoRan/next-safe-action/assets/84491737/d2e215ec-617b-4a4c-bb45-2f78f1fadf6f)

### Reproduction steps

1. `yarn build`
2. The error occured

### Expected behavior

Build successfully!

### Reproduction example

https://github.com/Sobee-Project/sobee-management

### Operating System

macOS Sonoma 14.4.1

### Library version

^7.0.0-next.39

**Comment by TheEdoRan** [comment]
I think the problem is that you have to install Next.js 14.3.0 canary version, as explained in #113 and beta version docs. Let me know if it fixes your problem, thanks.

**Comment by tuankietcoderr** [comment]
> I think the problem is that you have to install Next.js 14.3.0 canary version, as explained in #113 and beta version docs. Let me know if it fixes your problem, thanks.

TY i'll reply asap

**Comment by tuankietcoderr** [comment]
> I think the problem is that you have to install Next.js 14.3.0 canary version, as explained in #113 and beta version docs. Let me know if it fixes your problem, thanks.

Yeah i did resolved it, thank you for your time!
