### ISSUE TITLE
Action Error : Output is too short

### ISSUE THREAD

**Issue by Inalegwu** [TheEdoRan/next-safe-action#123]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

I found that the action errors when trying to return a redirect from an action, while trying to run an authentication flow in a project. I assume this isn't intended functionality as it isn't described anywhere in the docs.

### Reproduction steps

1. create an action that ends in a redirect
```
export const signup = action(signupSchema, async (input) => {
  const userExists = await db.query.users.findFirst({
    where: (user, { eq }) => eq(user.email, input.email),
  });

  if (userExists) {
    throw new Error("This email is already in use, Please try again");
  }

  const passwordHash = await argon.hash(input.password);

  const userId = generateIdFromEntropySize(10);

  await db.insert(users).values({
    id: userId,
    hashedPassword: passwordHash,
    email: input.email,
  });

  const session = await lucia.createSession(userId, {});
  const sessionCookie = lucia.createSessionCookie(session.id);

  cookies().set(
    sessionCookie.name,
    sessionCookie.value,
    sessionCookie.attributes,
  );

  return redirect("/dashboard");
});

```
2. attempt running said action
3. Result output is
```
Action error: output is too short
```

### Expected behavior

On successful action run, the redirect should be run.

### Reproduction example

https://github.com/Inalegwu/Pigeon

### Operating System

Windows 11

### Library version

6.2.0

**Comment by TheEdoRan** [comment]
I'm not sure this is related to next-safe-action. `Action error:` default prefix just means that an error occurred on the server.
Are you sure that the `redirect` function is reached while executing the action? If this is the case, please provide a link to a minimal reproduction repo/Stackblitz env, thanks!

**Comment by Inalegwu** [comment]
Sorry for the false positive. It was infact an error on my part. Thanks for the advice though, it did point me in the right direction
