### ISSUE TITLE
[BUG] Issue When Using useAction to Create Form with File Schema

### ISSUE THREAD

**Issue by KhoeLe** [TheEdoRan/next-safe-action#126]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

I am experiencing issues when creating a form that includes a file upload using useAction. Below is the code where the problem occurs:

### Reproduction steps

form-action.tsx
![image](https://github.com/TheEdoRan/next-safe-action/assets/63848705/44e94c6d-f450-4040-a1b0-1a2efe974a3c)

logic code handle submit
![image](https://github.com/TheEdoRan/next-safe-action/assets/63848705/bfa01294-696d-4b9b-a9a2-d8f9e9cf11a9)

form input upload file
![image](https://github.com/TheEdoRan/next-safe-action/assets/63848705/9ee6ab30-4f08-48e2-abc9-e971f94aa69d)

### Expected behavior

Problem occurs during the form submission process.
![image](https://github.com/TheEdoRan/next-safe-action/assets/63848705/2a481c28-ad14-4312-a6e2-3ba545df383d)

### Reproduction example

https://github.com/KhoeLe/next-safe-action.git

### Operating System

Windows 10

### Library version

 "next-safe-action": "^6.2.0",

### Additional context
if I remove the file from the formDataSchema and any related components, the form submits successfully
![image](https://github.com/TheEdoRan/next-safe-action/assets/63848705/bfe972ca-6f8e-4b99-a49b-6adf655bb325)

_No response_

**Comment by TheEdoRan** [comment]
Not related to next-safe-action, got the same error with your schema and without using this library. You need to pass the file in `FormData`, I suggest using [zod-form-data](https://www.npmjs.com/package/zod-form-data) on top of Zod to validate the form.

**Comment by KhoeLe** [comment]
Hello @TheEdoRan 

I am having issues using react-hook-form with a Zod schema for file uploads (z.instanceof(File)). I am encountering errors. Do you have any ideas for resolving this?

**Comment by andourys** [comment]
> Hello @TheEdoRan
> 
> I am having issues using react-hook-form with a Zod schema for file uploads (z.instanceof(File)). I am encountering errors. Do you have any ideas for resolving this?

File isn't a type noticed by nextjs if your node version is below >= 20.0. The potential alternative may be to try `z.instanceof(Blob))`, I haven't tried it out myself though

**Comment by ericd33** [comment]
I'm having a similar if not the same problem, is there a workaround?

**Comment by Jemaz** [comment]
For the people who are stuck on `Node.js 18 LTS` but can't upgrade above, unfortunately `z.instanceof(Blob))` doesn't work. Neither polyfilling with a Web-API compliant polyfill for the `File` class.

**Comment by agustin107** [comment]
Absolutely, updating the node version to `20` fix it!
