### ISSUE TITLE
Server action always return { serverError: true }

### ISSUE THREAD

**Issue by c-neri** [TheEdoRan/next-safe-action#15]
Hi, i'm making some api call in my serverAction, but i cannot get the error.
At the moment i'm trying somehting like this

```
export const createUser = action(createUserSchema, async (data) => {
    try {
        const res = await service({
            url: "/users/",
            method: "post",
            data,
        })
        return res.data
    } catch (error: any) {
        throw new Error(error?.response?.data?.message || "GenericError")
    }
})
```
In my client however i always get the  { serverError: true }

Maybe something like this ? 

```
export const action = createSafeActionClient({
    serverCustomErrorReturn: (e) => {
        return { myErrorKey:e}
    }
})

```

**Comment by TheEdoRan** [comment]
Thanks for opening this issue. That's the current intended behavior of the library, instead of rethrowing the error in the `catch` block you should just return a different value from there, then handle it on the client. `serverError` is there just to catch any unwanted errors that may happen on the server.
In this specific case, you could for example return an object like: `{ failure: "FETCH_ERROR" }` from the `catch` block.

**Comment by c-neri** [comment]
Thank you for the response, i tried, but if i do it, i'm not able to use the onError hook on the client, do you this is possible add some hook in the createSafeActionClient, so that we are able to, if we want, return the error message other than true?

**Comment by TheEdoRan** [comment]
So, the current way would be to use the `onSuccess` callback on the client, and check for failure from there. At this time, `onError` callback is reserved for server errors and validation errors, which are unwanted and uncontrollable by the user. It's [kinda like this approach](https://sachee.medium.com/200-ok-error-handling-in-graphql-7ec869aec9bc), but I'll se if I can come up with a better way to define and handle errors in an "errory" way. Keeping this issue open for now.

**Comment by TheEdoRan** [comment]
Hey, in the new beta version I added an optional configuration key named `unmaskServerError` to the safe action initializer. So, when you create a new client (via `createSafeActionClient`), you can now pass it to get on the client the actual message of the error that occurred server side.
You can install the beta version with: `npm i next-safe-action@beta`.
Let me know what you think about this solution, thanks!
