### ISSUE TITLE
useOptimisticAction only works if action returns an object

### ISSUE THREAD

**Issue by Apestein** [TheEdoRan/next-safe-action#16]
Just wanna say thanks and I love this lib. It's a game changer. There is just a small bug with useOptimisticAction hook. It only works if I pass an action that returns a object. If I pass an action that returns a boolean for example, the optimisticData object will always be empty {}.

```ts
const {
    execute,
    optimisticData,
    res,
    isExecuting
  } = useOptimisticAction(myAction, { isSaved: true }) //this works but if I pass an action that returns a boolean it will not
                                                           
```

**Comment by kiikoh** [comment]
Noticed the same problem

**Comment by TheEdoRan** [comment]
I apologize for the late reply, I was on vacation. So, you are "forced" to return an object from the action if you want to use the `useOptimisticAction` hook, because it works by spreading what you provide and merging it with an internal `__isExecuting__` key, in order to work. The optimistic API is still unstable and I'm not sure if there's a better way to handle this problem. If you know it, please let me know here or open a PR with the fix. Thank you!

**Comment by Apestein** [comment]
> I apologize for the late reply, I was on vacation. So, you are "forced" to return an object from the action if you want to use the `useOptimisticAction` hook, because it works by spreading what you provide and merging it with an internal `__isExecuting__` key, in order to work. The optimistic API is still unstable and I'm not sure if there's a better way to handle this problem. If you know it, please let me know here or open a PR with the fix. Thank you!

Understood, though you should mention it in the docs so people don't make this mistake. Also, you don't have to pass action as props btw. It works just fine even if you don't.

**Comment by TheEdoRan** [comment]
> you should mention it in the docs so people don't make this mistake.

Absolutely, will do it, thanks again.

> you don't have to pass action as props btw

Are you sure? I just tried and I encountered the same problem I had when I created the lib: [server state](https://github.com/TheEdoRan/next-safe-action/blob/main/packages/example-app/src/app/optimistic-hook/page.tsx#L17) (in RSC) when using `useOptimisticAction` doesn't update after using `revalidatePath` when I'm directly importing the action in the Client Component. Am I missing something?

**Comment by TheEdoRan** [comment]
I just tried again with the example-app Next.js project in this monorepo and I still encounter the same bug if I don't pass the action as prop from server to client: server state is not synced after `revalidatePath` is called in the server action's definition, so I cannot recommend it in the README, as it works "most of the time". If you want to reproduce it, clone this repo and test it (check out [this file](https://github.com/TheEdoRan/next-safe-action/blob/main/packages/example-app/src/app/optimistic-hook/addlikes-action.ts) and [this one](https://github.com/TheEdoRan/next-safe-action/blob/main/packages/example-app/src/app/optimistic-hook/page.tsx#L17) in particular, to see relevant code), then let me know if you're able to make it work without passing the action as prop. Open a new issue about this problem, if necessary. Thank you.

**Comment by Apestein** [comment]
> I just tried again with the example-app Next.js project in this monorepo and I still encounter the same bug if I don't pass the action as prop from server to client: server state is not synced after `revalidatePath` is called in the server action's definition, so I cannot recommend it in the README, as it works "most of the time". If you want to reproduce it, clone this repo and test it (check out [this file](https://github.com/TheEdoRan/next-safe-action/blob/main/packages/example-app/src/app/optimistic-hook/addlikes-action.ts) and [this one](https://github.com/TheEdoRan/next-safe-action/blob/main/packages/example-app/src/app/optimistic-hook/page.tsx#L17) in particular, to see relevant code), then let me know if you're able to make it work without passing the action as prop. Open a new issue about this problem, if necessary. Thank you.

https://github.com/Apestein/nsa-demo/tree/main

**Comment by TheEdoRan** [comment]
> https://github.com/Apestein/nsa-demo

Hey, sorry for the delayed reply, I just saw your comment after the issue was closed. By the way, I cloned your repo and the same thing happens: server state (with initial value of 42) never changes. If I click on the "Add likes" button it should update after the action finishes running, but it doesn't. So, it seems like `revalidatePath` doesn't work if you don't pass the action as a prop from the parent Server Component. Of course it works as expected if I pass the action as a prop.

**Comment by Apestein** [comment]
> > https://github.com/Apestein/nsa-demo
> 
> Hey, sorry for the delayed reply, I just saw your comment after the issue was closed. By the way, I cloned your repo and the same thing happens: server state (with initial value of 42) never changes. If I click on the "Add likes" button it should update after the action finishes running, but it doesn't. So, it seems like `revalidatePath` doesn't work if you don't pass the action as a prop from the parent Server Component. Of course it works as expected if I pass the action as a prop.

The reason it doesn't work with revalidatePath is because you need to use fetch. I've update my repo, check again.

**Comment by TheEdoRan** [comment]
> The reason it doesn't work with revalidatePath is because you need to use fetch. I've update my repo, check again.

Yes, fetch is re-run, but server state mutated by Server Action doesn't get updated though ([line 19](https://github.com/Apestein/nsa-demo/blob/main/packages/example-app/src/app/optimistic-hook/page.tsx#L19)). If you instead pass the action via prop from page.tsx to addlikes-form.tsx it works as expected. Let's say you're mutating data in your db and displaying it in the parent Server Component: by directly importing the action in Client Component it wouldn't sync the actual server state after mutation.
