### ISSUE TITLE
[BUG] `parsedInput` not being automatically typed

### ISSUE THREAD

**Issue by holahoon** [TheEdoRan/next-safe-action#170]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

I first want to thank you for open sourcing this library and I enjoy your Youtube video 👍 
I've migrated from v6 to v7, so I'm using the latest version: ^7.0.2.

I vaguely remember that in v6, `action(schema, async (field) => {...})` the `field` would get typed from the schema, but whatever reason, it stopped getting auto types (I have no clue why). So I decided to upgrade the package just for the heck of it.
But, even though I upgraded the package to the latests, it still doesn't get type autocomplete.

### Reproduction steps

Here's my code just to test out.
```typescript
import { z } from 'zod'
....
const test = actionClient.schema(z.object({username: z.string()})).action(async ({parsedInput}) => {
  // parsedInput is of type `any`
  const {username} = parsedInput
})
```
![image](https://github.com/TheEdoRan/next-safe-action/assets/42850638/29fdd73f-3e8a-4739-9b94-7619fb23a994)

### Expected behavior

I'm expecting the `parsedInput` to be of type whatever the schema is?

### Minimal reproduction example

https://github.com/holahoon/nextjs-next-safe-action-test

### Operating System

macOS

### Library version

7.02

### Next.js version

14.1.4

**Comment by TheEdoRan** [comment]
This should not happen, never happened to me and the library has tests that check for that before release. Can you please set up a minimal reproduction repo and then provide the link here? I need it to investigate the issue, otherwise it's impossible for me to help you just with this small code snippet.

By the way, never uploaded a video about next-safe-action on YouTube, but thanks for the kind words!

**Comment by holahoon** [comment]
Thanks for the quick response!
https://github.com/holahoon/nextjs-next-safe-action-test
Just created a quick test repository to test it out. I'm using node v20.12.2 if this helps.
Not sure if there's anything I might be missing

**Comment by kalvin807** [comment]
I had the same problem and I noticed that it only occur when typescript is >= 5.5 , I guess these are some changes in upcoming ts that breaks the typing

**Comment by TheEdoRan** [comment]
@holahoon that's weird. I cloned your repo, installed dependencies, left the code untouched, and I get the correct type for `parsedInput`:

![image](https://github.com/TheEdoRan/next-safe-action/assets/1337629/57d8e77c-d984-4c2e-8499-730ce46bc5db)

**Comment by TheEdoRan** [comment]
@kalvin807 The lastest stable TypeScript version is 5.4.5, maybe it's a 5.5 beta bug? Hope new internal TypeScript code won't break the library(/libraries) code. 🤦

**Comment by kalvin807** [comment]
I guess so, when I using `javascript and typescript nightly` extension, the typing fails to work

**Comment by TheEdoRan** [comment]
@kalvin807 I've just installed `typescript@beta` and I still get correct types. Maybe it was a nightly build bug?

![image](https://github.com/TheEdoRan/next-safe-action/assets/1337629/b0db64f9-557c-417a-a531-5764171ae2d6)

**Comment by TheEdoRan** [comment]
By the way @holahoon, this is out of scope, but you should create a `lib/safe-action.ts` file where you export the action client, and then create the action file and put `"use server";` at the start of it.

**Comment by holahoon** [comment]
That's bizarre how you get the correct type 🤔 I boils down to maybe a problem in my local environment.
Alright. It definitely was the `JavaScript and Typescript Nightly` extension 🤦🏻 Downgraded to the below version and it solves.
Thanks for looking into this issue! @kalvin807 @TheEdoRan 👍
![image](https://github.com/TheEdoRan/next-safe-action/assets/42850638/5fe7f943-7b70-4c1d-b323-b9a2d748f54c)
