### ISSUE TITLE
[BUG] Not compatible with Typescript >= 5.5.2

### ISSUE THREAD

**Issue by Talent30** [TheEdoRan/next-safe-action#180]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

`parsedInput` returning any, `schema` defined by Zod

Will provide a minimal repo soon. 

### Reproduction steps

1. Install Typescript 5.5.2
2. Create a safe action with Zod schema, check the type of `parsedInput`

### Expected behavior

`parsedInput` should have the correct type information

### Minimal reproduction example

[Code Sandbox link](https://codesandbox.io/p/devbox/jovial-feather-skcmjk?file=%2Fapp%2Fserver-action.ts%3A5%2C14&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxnvi63900072e689moq3kvr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxnvi63900022e689zs9rmgg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxnvi63900042e68l2ak8e0v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxnvi63900062e68t7h7abgh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxnvi63900022e689zs9rmgg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxnvi63900012e68g984fb3d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxnvjkh000022e6806o1zby2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A20%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A20%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxnvrbao00022e68ckqdp23z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A14%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A14%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fserver-action.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxnvi63900022e689zs9rmgg%2522%252C%2522activeTabId%2522%253A%2522clxnvrbao00022e68ckqdp23z%2522%257D%252C%2522clxnvi63900062e68t7h7abgh%2522%253A%257B%2522id%2522%253A%2522clxnvi63900062e68t7h7abgh%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clxnvi63900042e68l2ak8e0v%2522%253A%257B%2522id%2522%253A%2522clxnvi63900042e68l2ak8e0v%2522%252C%2522activeTabId%2522%253A%2522clxnvldsv003w2e68h37frulr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxnvldsv003w2e68h37frulr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxnvle1x0015dej16bbc8tlh%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Operating System

MacOS 14

### Library version

7.2.0

### Next.js version

14.2.4

**Comment by TheEdoRan** [comment]
Will look into it soon, thanks.

**Comment by pedro757** [comment]
I can confirm schema validations don't work with typescript 5.5.2

**Comment by TheEdoRan** [comment]
After some tests, I identified the problem in TypeSchema, which breaks with TypeScript 5.5. I've just opened an issue on the TypeSchema repo for this bug:

- decs/typeschema#61

**Comment by RolandRFuchs92** [comment]
I know this is a pretty new issue, but a quick easy workaround for me was to just downgrade typescript. I just locked at typescript 5.4.5 (I use the LSP that comes with Mason) for now, it seems to work perfectly.

**Comment by TheEdoRan** [comment]
@RolandRFuchs92 yes, the workaround is to downgrade to TypeScript v5.4. The issue appears to be related to a compiler change in TS 5.5.2, which broke [ts-patch](https://github.com/nonara/ts-patch) and so TypeSchema as well.

**Comment by TheEdoRan** [comment]
I've just released next-safe-action [v7.1.4-experimental.1](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.1.4-experimental.1), that should work fine with TypeScript 5.5. Note that **this version only works with Zod**, it's essentially the same codebase without TypeSchema support, as it's currently preventing the ability to upgrade to TS 5.5.

So, **if you're using Zod and TS 5.5**, you can install experimental next-safe-action with this command:

```sh
npm i next-safe-action@experimental # or pnpm, yarn
```

P.S.: Even though the tag is named "experimental", as explained above the codebase is essentially the same as the stable v7. It's named like that because I don't think this will be an actual library change, as it's nice to have multiple validation libraries support. However, it's also nice to use the latest TS version, so until TypeSchema is compatible with it, I think this is a good solution.

**Comment by damjtoh** [comment]
> I've just released next-safe-action [v7.1.4-experimental.1](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.1.4-experimental.1), that should work fine with TypeScript 5.5. Note that **this version only works with Zod**, it's essentially the same codebase without TypeSchema support, as it's currently preventing the ability to upgrade to TS 5.5.
> 
> So, **if you're using Zod and TS 5.5**, you can install experimental next-safe-action with this command:
> 
> ```shell
> npm i next-safe-action@experimental # or pnpm, yarn
> ```
> 
> P.S.: Even though the tag is named "experimental", as explained above the codebase is essentially the same as the stable v7. It's named like that because I don't think this will be an actual library change, as it's nice to have multiple validation libraries support. However, it's also nice to use the latest TS version, so until TypeSchema is compatible with it, I think this is a good solution.

Hey! Just to let you know is working for me using TS 5.5 and zod. Thanks for your amazing work!

**Comment by mattiaz9** [comment]
I'm trying the experimental version, but I can't destruct the response because is possibly undefined.

**Comment by TheEdoRan** [comment]
@mattiaz9 that's not an experimental version bug, it's the expected behavior since v7.0.0. The explanation for that can be found [here](https://github.com/TheEdoRan/next-safe-action/discussions/175#discussioncomment-9795963).

**Comment by mattiaz9** [comment]
> @mattiaz9 that's not an experimental version bug, it's the expected behavior since v7.0.0. The explanation for that can be found [here](https://github.com/TheEdoRan/next-safe-action/discussions/175#discussioncomment-9795963).

I see. I was previously using a pre-release of v7 and it wasn't yet the case, so I thought it was an error.

It didn't help the fact that in the docs that behavior is not shown. 
For instance in this example `res` is destructed without checking if `undefined`:
https://next-safe-action.dev/docs/getting-started#3-import-and-execute-the-action

**Comment by TheEdoRan** [comment]
@mattiaz9 

> It didn't help the fact that in the docs that behavior is not shown.

Fixed. It was left over from v6 docs.

**Comment by aniketbiprojit** [comment]
This should probably be added to docs as well if not already there.

**Comment by TheEdoRan** [comment]
@aniketbiprojit https://next-safe-action.dev/docs/troubleshooting#schema-and-parsedinput-are-typed-any-broken-types-and-build-issues

But I'll add a note on the getting started page too, soon.

**Comment by TheEdoRan** [comment]
This issue should be solved in [v7.2.0](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.2.0). next-safe-action now ships with a built-in system for supporting multiple validation libraries, at this time Zod (the default one), Valibot and Yup. You can now use them even with the Edge Runtime and obviously with TS >= 5.5. More information about that in [this discussion](https://github.com/TheEdoRan/next-safe-action/discussions/201) and on [this page](https://next-safe-action.dev/docs/recipes/validation-libraries-support) of the website.

Please let me know if you encounter any bugs when updating to v7.2.0, thanks!

**Comment by benjick** [comment]
Thanks for the reply! I've long since updated, love the new version v
