### ISSUE TITLE
[BUG] Valibot schema not working

### ISSUE THREAD

**Issue by pedro757** [TheEdoRan/next-safe-action#181]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

I get this error from tsserver: 

```
Argument of type 'ObjectSchema<{ readonly MyField: StringSchema<undefined>; }, undefined>' is not assignable to parameter of type 'ZodType<any, ZodTypeDef, any> | ((prevSchema: undefined) => Promise<ZodType<any, ZodTypeDef, any>>)'. [2345]
```

### Reproduction steps

1. Create and use an action with valibot like this
```typescript 
"use server";

import { string, object } from "valibot";

const createSchema = object({
  MyField: string(),
});

export const createSomething = action
  .schema(createSchema)
  .action(async function ({ parsedInput }) {
    // parsedInput is of type unknown
  });
```
The error I get is this:
```
Argument of type 'ObjectSchema<{ readonly MyField: StringSchema<undefined>; }, undefined>' is not assignable to parameter of type 'ZodType<any, ZodTypeDef, any> | ((prevSchema: undefined) => Promise<ZodType<any, ZodTypeDef, any>>)'. [2345]
```
It looks like it's expecting a zod type

### Expected behavior

I expected to work with valibot

### Minimal reproduction example

The code is in the description of the issue

### Operating System

Linux

### Library version

7.1

### Next.js version

14.2.4

**Comment by TheEdoRan** [comment]
Need a link to a minimal reproduction example.

**Comment by TheEdoRan** [comment]
This is related to (either or both):

- #180 
- https://github.com/decs/typeschema/issues/60

I'm closing the issue as there are already issues open about this problem.

**Comment by TheEdoRan** [comment]
Hey @pedro757, please try to update to the latest stable release and set up validation with Valibot. Now next-safe-action ships with built-in support for multiple validation libraries. Related discussion [here](https://github.com/TheEdoRan/next-safe-action/discussions/201) and docs page [here](https://next-safe-action.dev/docs/recipes/validation-libraries-support).
