### ISSUE TITLE
[BUG] TypeError in useAction when using a yup schema

### ISSUE THREAD

**Issue by valentinludu** [TheEdoRan/next-safe-action#183]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

I tryied a zod schema and works fine.

But with a yup schema:
- useAction hook throws a type error when used with an action that has an yup schema.
- defineMetadataSchema throws a type error when defining a yup schema

### Reproduction steps

Using "typescript": "^5.4.2",  "@typeschema/yup": "^0.13.3", "next": "14.1.1", "react": "^18.2.0", "next-safe-action": "^7.1.0"

My client:

```
import type { IronSession } from 'iron-session';
import { getIronSession } from 'iron-session';
import { cookies } from 'next/headers';
import { createSafeActionClient } from 'next-safe-action/typeschema';
import * as yup from 'yup';

export const actionClient = createSafeActionClient({
  handleReturnedServerError: handleServerError,
  defineMetadataSchema: () => {
    return yup.object({
      actionName: yup.string()
    });
  }
})
.use(async ({ next }) => {
    const result = await next({ ctx: null });
    // log.info('LOGGING MIDDLEWARE FOR ACTION');
    return result;
})
.use(async ({ next }) => {
    const session = await getIronSession<SessionData>(cookies(), {});
    return next({
      ctx: { session }
    });
  });
```

defineMetadataSchema throws:

<img width="937" alt="Screenshot 2024-06-25 at 13 42 57" src="https://github.com/TheEdoRan/next-safe-action/assets/25636858/f77362f8-6874-494f-881b-b2fea5da1d31">

Using useAction in the FE throws a TypeError:

`const { execute, executeAsync, result, status, reset, isIdle, isExecuting, hasSucceeded, hasErrored } =
    useAction(actionOnboarding);`

<img width="1016" alt="Screenshot 2024-06-25 at 13 41 45" src="https://github.com/TheEdoRan/next-safe-action/assets/25636858/4e380b6d-22e9-4c81-94e7-93d61484ec20">

useAction expects Zod:

<img width="769" alt="Screenshot 2024-06-25 at 13 55 38" src="https://github.com/TheEdoRan/next-safe-action/assets/25636858/9acfd6f3-16e9-4cf6-b139-e56ed9a9ba57">

### Expected behavior

useAction should expect the yup schema and not the zod one.
defineMetadataSchema should accept yup.

### Minimal reproduction example

https://github.com

### Operating System

macOS

### Library version

7.1.0

### Next.js version

14.1.1

**Comment by TheEdoRan** [comment]
Cannot reproduce the issue:

![image](https://github.com/TheEdoRan/next-safe-action/assets/1337629/ffe70b98-6b13-4490-b87e-180f231b0643)

My guess is you just need to uninstall zod and @typeschema/zod, maybe delete node_modules and lockfile as well, then reinstall dependencies and reload the editor. TypeSchema works with dynamic imports and TypeScript magic, so it causes errors sometimes. If the issue persists I'll need a reproduction link to investigate this.

**Comment by valentinludu** [comment]
I tested it inside a CodeSandbox and the errors are not present.
So it must be something on my end.
I don't have "zod" and "@typeschema/zod" installed so I will try to delete node_modules, lock file and see if I get it to work.

Thank you for the quick response. I will try it out and come back if I have any issues.

**Comment by TheEdoRan** [comment]
Any updates on this issue?

**Comment by valentinludu** [comment]
After deleting package-lock and node_modules, now useAction types are working.
On the other hand defineMetadataSchema is still throwing that type error.
I just added @ts-ignore it for now so I can continue my work.

**Comment by TheEdoRan** [comment]
Kinda weird, have you tried reloading the editor?

**Comment by valentinludu** [comment]
Most certainly it's because I am in a monorepo. Unfortunately I can't pin where the actual problem is.

**Comment by TheEdoRan** [comment]
Does [v7.2.0](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.2.0) solve this issue? next-safe-action now ships with built-in support for multiple validation libraries. You can find more information about that in [this discussion](https://github.com/TheEdoRan/next-safe-action/discussions/201) and on [this page](https://next-safe-action.dev/docs/recipes/validation-libraries-support) of the website.

**Comment by valentinludu** [comment]
After I updated the lib to the latest version 7.4.1, all the TypeScript errors are gone. I tested with TypeScript 5.4 and 5.5 because I had an issue with v5.5. as well and that is fixed too.

Thanks a million. Issue can be closed!

**Comment by TheEdoRan** [comment]
That's great, thanks for the feedback!
