### ISSUE TITLE
Suggestion: Make error handling more flexible

### ISSUE THREAD

**Issue by ErfanEbrahimnia** [TheEdoRan/next-safe-action#19]
Hello @TheEdoRan,

First of all thanks for building this library!

I saw you've included a new flag called "unmaskServerError" in the latest update, and I think having this option is a great idea. However, I've noticed that setting it to `true` exposes all types of errors to the client, which could pose a security risk.

I'd like to propose an improvement: offering users of this library the ability to specify which errors should be sent back to the client. This can be achieved by allowing users to pass a function as the `unmaskServerError` parameter, instead of just a boolean value.

Here's how this change can be implemented:

```typescript
// Modify the definition of the `unmaskServerError` parameter like this:
// unmaskServerError?: boolean | ((e: unknown) => { serverError: string });

// ...

if (createOpts?.unmaskServerError) {
    // If 'unmaskServerError' is a function, let the user handle the error
    if (typeof createOpts.unmaskServerError === "function") {
        return createOpts.unmaskServerError(e);
    }

    if (isError(e)) {
        return { serverError: (e as Error).message };
    }

    if (typeof e === "string") {
        return { serverError: e };
    }

    // If the error type cannot be logged, issue a warning to the user.
    console.warn("Could not log server error:", e);
}
```

You can use this feature when creating a client like this:

```typescript
import { DbError } from "./errors";

export const action = createSafeActionClient({
  unmaskServerError: (e: unknown) => {
    if (e instanceof DbError) {
      return { serverError: e.message };
    }

    return {
      serverError: "Oops!",
    };
  },
});
```

Here's an example of an action that throws an error:

```typescript
export const deleteUser = action(input, async ({ userId }: any) => {
 try {
    await db.deleteUserById(userId);
 } catch {
    throw new DbError("Couldn't delete user")
 }

  return {
    deleted: true,
  };
});
```

Currently, I'm using this modification in my own fork of the library. I'd appreciate hearing your thoughts on whether it would make sense to incorporate this enhancement into the official library

Related: https://github.com/TheEdoRan/next-safe-action/issues/15

**Comment by TheEdoRan** [comment]
Hi and thanks for your suggestion.
I think it's much better than the current way of handling server errors. I released a new beta (code is in [beta branch](https://github.com/TheEdoRan/next-safe-action/tree/beta)) with this feature implemented, just slightly "adjusted": `unmaskServerError` is now called `handleServerErrorFunction`, which is an optional Promise. If you provide it to the initializer, the client switches to manual error handling.

I think it's less confusing for the user if the type is just a function, and not `Promise | boolean`, also now the name is a better fit in my opinion. Let me know what you think about it. Thanks!

**Comment by ErfanEbrahimnia** [comment]
Appreciate you putting the code in the library already. I was about to submit a PR.

The naming and changes you made make sense. I chose my way to maintain compatibility with the current release. Your approach is better if that's not necessary.

**Comment by TheEdoRan** [comment]
> I chose my way to maintain compatibility with the current release.

Yeah, I totally understand that, but I released the error unmasking feature a few days ago, as an "advanced" init option, so I don't think che name change affects many users. It's better to rename it now (to a clearer name, avoiding confusion) when the feature is new than later, imho. What do you think?

**Comment by ErfanEbrahimnia** [comment]
Got it, then it shouldn't be an issue. Thanks for clarifying

**Comment by TheEdoRan** [comment]
I renamed `handleServerErrorFunction` to `handleReturnedServerError`, which I think is an even better name. Last time, I promise.
