### ISSUE TITLE
[BUG] Attempted import error: 'useActionState' is not exported from 'react'

### ISSUE THREAD

**Issue by holahoon** [TheEdoRan/next-safe-action#203]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

When building next.js, it fails to compile with error:
```
  ▲ Next.js 14.2.5
  - Environments: .env.production

   Creating an optimized production build ...
Failed to compile.

./node_modules/.pnpm/next-safe-action@7.2.0_next@14.2.5_react-dom@18.3.1_react@18.3.1_yup@1.4.0_zod@3.23.8/node_modules/next-safe-action/dist/stateful-hooks.mjs
Attempted import error: 'useActionState' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/.pnpm/next-safe-action@7.2.0_next@14.2.5_react-dom@18.3.1_react@18.3.1_yup@1.4.0_zod@3.23.8/node_modules/next-safe-action/dist/stateful-hooks.mjs
./node_modules/.pnpm/next-safe-action@7.2.0_next@14.2.5_react-dom@18.3.1_react@18.3.1_yup@1.4.0_zod@3.23.8/node_modules/next-safe-action/dist/hooks.mjs
./src/app/(main)/(auth)/reset-password/_components/reset-password-form.tsx
```

### Reproduction steps

I deleted `pnpm-lock.yaml` and `node_modules` folders to clean install the package again.
Ran `pnpm install` to install all of my dependencies and ran `pnpm next run build` to build the code.
All of a sudden, build fails which wasn't failing before.
Am I using a wrong version?

### Expected behavior

Expected the build to compile, but fails with `Attempted import error: 'useActionState' is not exported from 'react' (imported as 'React').`

### Minimal reproduction example

private repo

### Operating System

mac OS M2

### Library version

7.2.0

### Next.js version

14.2.4

**Comment by holahoon** [comment]
I previously used 7.0.2 version, then updated to 7.2.0 to see if it solves, but no luck

**Comment by holahoon** [comment]
Ah, https://github.com/TheEdoRan/next-safe-action/issues/113

**Comment by TheEdoRan** [comment]
next-safe-action v7 works with Next.js 14 too. I mistakenly exported `useStateAction` hook from `/hooks` path in v7.2.0, while it should only be exported from `/stateful-hooks` path. [v7.2.1](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.2.1) should fix this build issue, please let me know.

**Comment by holahoon** [comment]
Hmm, well, it seems like it Next.js requires React >= 19.0.0 when updating the Next.js version to `14.3.0-canary.40` which I don't want to use 19 yet 🤔

**Comment by TheEdoRan** [comment]
Can't you use Next 14.2.5?

**Comment by holahoon** [comment]
https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.2.1 fixed it. Thanks!

**Comment by holahoon** [comment]
> Can't you use Next 14.2.5?

Yeah, I def can. I just thought I had to upgrade to `14.3.0-canary.40` which requires react >=19.
