### ISSUE TITLE
[BUG] Module not found when using latest version

### ISSUE THREAD

**Issue by simonri** [TheEdoRan/next-safe-action#204]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

After updating from 7.1.3 to 7.2.1 I get the following error:

```
 ⨯ ./node_modules/next-safe-action/dist/index.mjs:1:1
Module not found: Can't resolve './adapters/zod'
> 1 | import { zodAdapter } from "./adapters/zod";
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | import { SafeActionClient } from "./safe-action-client";
  3 | import { DEFAULT_SERVER_ERROR_MESSAGE } from "./utils";
  4 | import {
```

### Reproduction steps

Server action with zod schema. 

### Expected behavior

No error.

### Minimal reproduction example

Private repo

### Operating System

Windows 11

### Library version

v7.2.1

### Next.js version

15.0.0-canary.72

**Comment by TheEdoRan** [comment]
Need a minimal reproduction example, because I can run and build the project fine, even with Next.js 15:

![image](https://github.com/user-attachments/assets/8c50c8fd-0920-4a5a-a369-3fbe69da24d5)

**Comment by TheEdoRan** [comment]
Yeah, but I need a link to a repo to investigate on this issue, otherwise it's pretty difficult, since it works fine for me. Should be pretty easy to set up a minimal project.

**Comment by TheEdoRan** [comment]
Update: please let me know if [v7.2.2-beta.1](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.2.2-beta.1) solves your issue, thanks. You can install it with:

```sh
npm i next-safe-action@beta # or pnpm, yarn
```

I re-enabled bundling, Windows might not like it turned off.

**Comment by TheEdoRan** [comment]
> The issue only happens when using --turbo. The same code without --turbo works.

Ah, that's very interesting, thank you for your feedback! Gonna merge beta into main right now and release v7.2.2 stable.

**Comment by TheEdoRan** [comment]
Thank you!
