### ISSUE TITLE
[BUG] `onExecute` callback not executing

### ISSUE THREAD

**Issue by steveiliop56** [TheEdoRan/next-safe-action#216]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

Hello,

I tried to use the `onExecute` callback on the `useAction` hook but I noticed that it never actually runs the code, while both `onSuccess` and `onError` callbacks work just fine. 

### Reproduction steps

1. Run my example (with `npm run dev`)
2. Click the `Click me` text
3. The text is never set to `executing` it only changes to `executed`

### Expected behavior

When I click the `Click me` button the text should change to `executing` and after 2 seconds it should change to `executed`.

### Minimal reproduction example

https://github.com/steveiliop56/nextjs-next-safe-action-bug

### Operating System

Ubuntu 22.04.3 LTS (running on WSL)

### Library version

7.4.2

### Next.js version

14.2.5

**Comment by TheEdoRan** [comment]
Thank you for finding this bug and providing a reproduction example! The issue should be fixed in [v7.4.3](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.4.3).
