### ISSUE TITLE
Can I create an action without input?

### ISSUE THREAD

**Issue by pedro757** [TheEdoRan/next-safe-action#23]

**Comment by TheEdoRan** [comment]
Yes, just pass an empty Zod object schema when you're defining a new action, like this:

```typescript
const schema = z.object({});

export const testAction = action(schema, async () => {
  return { ok: true };
});
```

**Comment by m1yon** [comment]
I get a type error if I call the resulting function without sending it an empty object. Anyway to fix this?

<img width="688" alt="CleanShot 2023-12-06 at 16 28 44@2x" src="https://github.com/TheEdoRan/next-safe-action/assets/37197876/c1455eae-b966-463b-8d11-a0fe0a1a13db">

**Comment by TheEdoRan** [comment]
@m1yon If you define a safe action with `z.object({})` as input schema, you're required to pass an object from the client.
You can instead define an action with `z.void()` as input schema to call the function without arguments.

Example:

```typescript
// action.ts
"use server";

export const signoutAction = action(z.void(), async () => {
    // ...
  }
);
```

```tsx
// component.tsx
"use client";

// ...
signoutAction();
// ...
```
