### ISSUE TITLE
[BUG] Enabling `throwValidationErrors` does not allow error propagation to `handleServerError`

### ISSUE THREAD

**Issue by sheikhshack** [TheEdoRan/next-safe-action#247]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

The current functionality of `throwValidationErrors: true` doesn't quite propagate nicely to `handleServerError` which was initially expected behaviour as per https://github.com/TheEdoRan/next-safe-action/discussions/171#discussioncomment-9830336

### Reproduction steps

1. Enable `throwValidationErrors` at instantiation of the safe action client
2. In `handleReturnedServerError`, log all errors (or optionally errors that are of instance `ActionValidationError`)
3. Try to trigger a validation error for any safe-actions.

Using the above, it seems that the errors weren't quite propagated nicely to the `handleReturnedServerError` callbacks, and are instead thrown directly as a typical unhandled NextJS server action errors. 

### Expected behavior

Expected that all validation errors would have propogated nicely such that i can access the validation errors via the handleReturnedServerError

### Minimal reproduction example

https://codesandbox.io/p/sandbox/react-hook-form-field-array-append-remove-df816

### Operating System

macOS

### Library version

7.7.1

### Next.js version

14.2.3

**Comment by TheEdoRan** [comment]
Hi, this is the expected behavior as of now, since validation errors aren't and shouldn't be considered server errors. If you set `throwValidationErrors` to `true`, they go to a "different path" when they get thrown. I'm not sure if changing this behavior would be the right choice, I've always assumed this is the correct execution flow.
