### ISSUE TITLE
[BUG] Jest error "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by freirepaulo** [TheEdoRan/next-safe-action#252]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

First of all, I would like to thank you for the excellent work you have been doing with this library. However, I am facing an issue in my new project.

When I try to run my tests (just a simple test), it returns this error within the dist of safe-action. I noticed that a similar issue was opened in the past and resolved, but the problem seems to have returned:

![Screenshot 2024-08-29 at 15 47 10](https://github.com/user-attachments/assets/b6b7aa9c-5eae-40e5-bd8a-b9ad6e1ba3cd)

These are the dependencies I am using:
![Screenshot 2024-08-29 at 15 49 20](https://github.com/user-attachments/assets/945a6c0d-d78a-4683-8259-c24b006253e3)

### Reproduction steps

1. add the library
2. try to run a base unit test

is also important to say that the page.tsx is a server component and the SearchArea.tsx is a client component.

this the unit test that is breaking:
![Screenshot 2024-08-29 at 15 51 31](https://github.com/user-attachments/assets/98f02f48-d06a-46ef-ac97-19699d61f8be)

### Expected behavior

the test should pass 

### Minimal reproduction example

private repo

### Operating System

macOS

### Library version

7.8.0

### Next.js version

14.2.5

### Node.js version

21.7.3

**Comment by TheEdoRan** [comment]
Hi, please set up a public repo or a CodeSandbox project with a minimal reproduction of the issue so I can investigate the problem, thanks.

**Comment by freirepaulo** [comment]
@TheEdoRan https://github.com/freirepaulo/next-safe-action public repo that has the issue - to reproduce is just run yarn and yarn test 

![Screenshot 2024-08-29 at 18 18 12](https://github.com/user-attachments/assets/ece80e11-86ba-479b-8504-5f84f2a5231b)

**Comment by freirepaulo** [comment]
If I change all the imports and exports in the hook.mjs and index.mjs resolves the problem, but I don't know what will impact the library structure....

![Screenshot 2024-08-30 at 11 46 34](https://github.com/user-attachments/assets/fdf633a1-e6b3-4d18-91f1-4953a375f96f)
![Screenshot 2024-08-30 at 11 48 06](https://github.com/user-attachments/assets/437f9592-59ad-4984-89cf-47e793318d91)

**Comment by TheEdoRan** [comment]
Thank you for providing the repro. I solved the issue on my end by setting this option in `next.config.mjs`:

```diff
const nextConfig = {
+  transpilePackages: ["next-safe-action"],
};
```

![image](https://github.com/user-attachments/assets/735b4a23-4211-43cc-8750-ae10bdfc8c5c)


Vitest should be a better testing framework though, if you can switch to it. Let me know if setting that option fixes the issue for you as well, thanks!
