### ISSUE TITLE
Dist files contain incorrect types

### ISSUE THREAD

**Issue by tzilmarn** [TheEdoRan/next-safe-action#27]
The version on npm contains the following.
Notice the `<const Schema extends z.ZodTypeAny` .etc.
For some reason they contain `const` which Typescript treats as  a type.

```typescript
/**
 * Initialize a new action client.
 * @param createOpts Options for creating a new action client.
 * @returns {Function} A function that creates a new action, to be used in server files.
 *
 * {@link https://github.com/TheEdoRan/next-safe-action/tree/main/packages/next-safe-action#project-configuration See an example}
 */
declare const createSafeActionClient: <Context>(createOpts?: {
    handleServerErrorLog?: ((e: Error) => MaybePromise<void>) | undefined;
    handleReturnedServerError?: ((e: Error) => MaybePromise<{
        serverError: string;
    }>) | undefined;
    middleware?: (() => MaybePromise<Context>) | undefined;
} | undefined) => <const Schema extends z.ZodTypeAny, const Data>(schema: Schema, serverCode: ServerCode<Schema, Data, Context>) => SafeAction<Schema, Data>;


```

**Comment by r1tsuu** [comment]
Isn't it feature of TS 5 https://xebia.com/blog/typescript-5-0-and-the-new-const-modifier-on-type-parameters/ 
I checked and with 4 my build fails, but with 5 ok. But would be good to add compatibility

**Comment by TheEdoRan** [comment]
As @r1tsuu just said, I think you're referring to [const type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters), introduced in TypeScript 5.0, which is the minimum required version for this library. Generics are marked as `const` to get better type inference: return types would be looser without this type modifier.

> for some reason my Next.js app doesn't want to build with TS 5

This is weird, I've had no issues running TS >5.0 with multiple Next.js 13 projects. If you want, you can open a new issue about this specific problem.
