### ISSUE TITLE
[BUG] : {imported module [project]/apps/app/src/app/http/safe-action.ts [app-client] (ecmascript)}.authActionClient.schema is not a function

### ISSUE THREAD

**Issue by Heitorh3** [TheEdoRan/next-safe-action#274]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

Error when trying to use safe-action library.

![image](https://github.com/user-attachments/assets/9a8acdef-630c-4e44-b95d-6a08f11256c2)

`safe-action`
![safa-action](https://github.com/user-attachments/assets/40e01742-9611-4e55-88cc-613a5a7da165)

`delete-user`

![delete-user](https://github.com/user-attachments/assets/845eb8d3-0375-4ae6-bf05-96c9f49d12b2)

Thank you!

### Reproduction steps

Execute project: 
 pnp run dev

### Expected behavior

I expected delete user

### Link to a minimal reproduction of the issue

https://github.com/Heitorh3/proflin-sistema/

### Operating System

Linux pc 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Library version

7.9.3

### Next.js version

19

### Node.js version

20.11.0

**Comment by TheEdoRan** [comment]
You should remove `"use server"` directive in the safe-action.ts file, place it at the start of every action file. If the validation schema is used on the client too, you should place and export it from a separate file. The docs should explain this pretty well, let me know if these steps solve your issue.

**Comment by Heitorh3** [comment]
Thank you, it worked.
