### ISSUE TITLE
[BUG] When redirecting to `onError` on the server, `onError` is not called on the client, but `onSuccess` is called on the client

### ISSUE THREAD

**Issue by MrOxMasTer** [TheEdoRan/next-safe-action#281]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

When redirecting to `onError` on the server, `onError` is not called on the client, but `onSuccess` is called on the client

![image](https://github.com/user-attachments/assets/af381c4e-f647-4623-9a78-d64bd837f662)
![image](https://github.com/user-attachments/assets/13aec23f-0ab6-48ac-95ca-2b5f5ec1610f)
![image](https://github.com/user-attachments/assets/5403816b-86d2-4e61-902e-55711293ec6a)

### Reproduction steps

1. Create a `server action` with `onError`
2. Inside `onError` in the `server action` call `redirect` from `next/navigation`
3. Try to handle the error on the client side: call methods together with the console: `onError` and `onSuccess`.

### Expected behavior

Calling `onError` on both server and client sides

### Link to a minimal reproduction of the issue

https://codesandbox.io/

### Operating System

Windows 10

### Library version

7.9.3

### Next.js version

15-RC-0

### Node.js version

20.16.0

### Additional context

Can't make an example: codesandbox takes a very long time to load and lags / github repository I can't open either.
P.S - I use `@next-safe-action/adapter-react-hook-form/hooks`.

**Comment by TheEdoRan** [comment]
If I understand this correctly, this is the correct behavior. `redirect` should trigger the `onSuccess` hook callback.

**Comment by MrOxMasTer** [comment]
> If I understand this correctly, this is the correct behavior. `redirect` should trigger the `onSuccess` hook callback.

Question, how to catch this `redirect` then. There is no `hasRedirect` here:
![image](https://github.com/user-attachments/assets/813e8779-e986-4779-8525-6d3ec03371e5)

**Comment by MrOxMasTer** [comment]
> If I understand this correctly, this is the correct behavior. `redirect` should trigger the `onSuccess` hook callback.

In my opinion, `redirect` is called not only in successful cases, but also in erroneous cases. Taking into account that this redirect cannot be caught in any way, it turns out that I cannot call `toast` in an unsuccessful case (if the user is not found), even with a condition, because `redirect` returns nothing. 
Then I have to call the redirect on the client side.

But as far as I understand, if I call `redirect` in `onSuccess`, then `onSuccess` will work successfully on the client as well. As if it's not intuitive that `onSuccess` is called in both cases

**Comment by TheEdoRan** [comment]
@MrOxMasTer Yes, unfortunately that's due to Next.js internals. It just returns `undefined` on redirects. I'd say the easiest way is to check if `typeof data === "undefined"`.

**Comment by MrOxMasTer** [comment]
Here either add a similar `hasRedirect`, as it is on the server, or call `onError` in case of an error (which is more intuitive: if an error occurs on the server, an error occurs on the client, or rather interception of this error).

**Comment by MrOxMasTer** [comment]
> @MrOxMasTer Yes, unfortunately that's due to Next.js internals. It just returns `undefined` on redirects. I'd say the easiest way is to check if `typeof data === "undefined"`.

Well, I preempted you, if you can come up with something, that would be great, but for now only like this: `typeof data === “undefined”`.

**Comment by JClackett** [comment]
@MrOxMasTer maybe not ideal for your use case, but id consider moving your toast setting to the server, using cookies and then having a generic toast handler component at the root of your app. This way you can do:

```ts
await setToast("stuff")
redirect("/somewhere")
````

I do this and it works fairly well, of course sometimes you need to do it on the client, but id venture a guess and say that you wouldn't be redirecting in those cases anyway - you can can safely check for result.
