### ISSUE TITLE
[BUG] Typescript "implicitly has an 'any' type"

### ISSUE THREAD

**Issue by agamm** [TheEdoRan/next-safe-action#285]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

When using vscode with next-safe-action I get the following:
![image](https://github.com/user-attachments/assets/e55a9e03-d0f4-4168-bceb-19318be8727d)

### Reproduction steps

My tsconfig:
```
{
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "target": "ES2017"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

### Expected behavior

I expect typescript to understand the type in my vscode automatically.

### Link to a minimal reproduction of the issue

https://github.com/agamm/next-safe-action-bug

### Operating System

Windows 11 - WSL ubuntu

### Library version

7.9.6

### Next.js version

15.0.0

### Node.js version

20

### Additional context

I think it's more of a vscode setting.
Just this file is relevant:
https://github.com/agamm/next-safe-action-bug/blob/main/src/app/actions/test.ts

**Comment by TheEdoRan** [comment]
Where is the `actionClient` exported from? I don't see a `lib/` folder in the reproduction repo you provided.

**Comment by agamm** [comment]
> Where is the `actionClient` exported from? I don't see a `lib/` folder in the reproduction repo you provided.

Added, but it isn't needed, I still see the vscode wiggly line. It's because of typescript.

**Comment by TheEdoRan** [comment]
> Added, but it isn't needed

It's very much needed! You can't create actions without the action client. I think that's the bug. If you follow the getting started page ([step 1](https://next-safe-action.dev/docs/getting-started#1-instantiate-a-new-client)), and place that content in `src/lib/safe-action.ts`, the error should go away. The tsconfig seems correct to me, maybe you just need to restart the TS server/reload the VS Code window after creating that file.

**Comment by agamm** [comment]
But this might catch up to next-safe-action when people upgrade to 15.

**Comment by TheEdoRan** [comment]
That's pretty weird, I've just tried with Next.js 15 and everything seems to work fine on my end. 🤔

**Comment by agamm** [comment]
Let's close for now, I'll try to upgrade in a few weeks an reopen if this happens again.
