### ISSUE TITLE
[BUG] Cloudflare Edge Workers Exception

### ISSUE THREAD

**Issue by isaacrowntree** [TheEdoRan/next-safe-action#291]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

When using the code examples provided I'm able to get the code working locally but on production the Cloudflare worker throws this error:

```
"exceptions": [
    {
      "stack": "    at S (bundledWorker-0.584737685915216.mjs:350:11)\n    at Ct (bundledWorker-0.584737685915216.mjs:700:15)\n    at Q (bundledWorker-0.584737685915216.mjs:679:10)",
      "name": "TypeError",
      "message": "This ReadableStream is disturbed (has already been read from), and cannot be used as a body.",
      "timestamp": 1730248897891
    }
  ],

"request": {
      "url": "https://campermate.com/en/submissions/poi/update/72058?user_uid=anonymous-web",
      "method": "POST",
```

### Reproduction steps

You will need to create a nextjs 14 server action and form on Cloudflare Pages. Then it will be unable to run the POST request at all...

### Expected behavior

It should POST with no error.

### Link to a minimal reproduction of the issue

https://campermate.com/en/submissions/poi/update/72058?user_uid=anonymous-web

Just submit this form with a comment text only.

### Operating System

MacOS

### Library version

7.9.9

### Next.js version

14.2.16

### Node.js version

22

**Comment by TheEdoRan** [comment]
Does this happen just with actions defined using next-safe-action or with regular actions too?

**Comment by isaacrowntree** [comment]
OK I think I've narrowed this down. This is not your code - it's the @edge-csrf/nextjs package. Sorry to bother you!
