### ISSUE TITLE
Envs not working in Server Actions

### ISSUE THREAD

**Issue by Makisuo** [TheEdoRan/next-safe-action#3]
I have this weird thing of envs not showing up in my server actions, is that intended or some weird NextJS shenanigans?

**Comment by TheEdoRan** [comment]
Hey, thanks for opening this issue. I just tried and it works fine for me, can you please add a code snippet or a link to a repo with a reproduction of the bug? Thank you.

**Comment by Makisuo** [comment]
I found the bug, I'll try to make a reproduction repo later today.

Basically what I found is Nextjs with Server Actions doesn't seem be checking which env variables are being used so its not loading them in development mode (?).

So basically 
`ts
export const createWebsiteAction = action({ input }, async (input) => {
	console.log(process.env.LAGO_API_KEY)
})
`

right now this env is undefined, though if I add to my page.tsx that I use my server action in like this

`ts
console.log(process.env.LAGO_API_KEY)
`

the env in the server actions gets defined. Seems like a weird nextjs dev server bug, works fine in production since ofc all envs are just loaded in the environment directly.

**Comment by TheEdoRan** [comment]
Hey, I tried to reproduce this issue without success. Here's my test code: [next-actions-env](https://github.com/TheEdoRan/next-actions-env), I also pushed `env.local` file so if you clone the repo you'll get it. Environment variables are logged in server console on my end (Windows 11 with Ubuntu 22.04 - WSL2). Did I miss something?

**Comment by TheEdoRan** [comment]
Closing the issue for now. If you are still having this problem, provide a reproduction example and I'll reopen it. Thank you!
