### ISSUE TITLE
Transforms don't work

### ISSUE THREAD

**Issue by lucgagan** [TheEdoRan/next-safe-action#30]
Would expect `referenceArticles` to be `string[]`.

<img width="511" alt="Screenshot 2023-10-22 at 4 02 14 PM" src="https://github.com/TheEdoRan/next-safe-action/assets/134170834/ba53dc2c-d765-486c-844b-0a844ea8b5e7">

**Comment by TheEdoRan** [comment]
I think the problem comes from using `z.input` both for client input and parsed input in the server action code function. Instead, `z.input` should be used just for client input, while server parsed input should use `z.infer`. Should be a pretty easy fix, thank you for opening this issue!
