### ISSUE TITLE
[BUG] The "use server" file can only export async functions. #306

### ISSUE THREAD

**Issue by sagar-jani** [TheEdoRan/next-safe-action#307]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

Even though I am following an example - https://github.com/TheEdoRan/next-safe-action/blob/main/apps/playground/src/app/(examples)/with-context/edituser-action.ts#L3

This gives me an error - Add "async" to the function declaration or return a Promise.

### Reproduction steps

Below is the action
```
'use server';

import { authAction } from './safe-action';
import { updateLenderSchema } from './schema';

export const updateLenderAction = authAction
  .schema(updateLenderSchema)
  .metadata({
    permission: 'lenders:edit'
  })
  .action(
    async ({
      parsedInput: { id, name, status, trailRate, aliases: string[] } ,
      ctx:{ user, supabase },
    }) => {
      //Action
      console.log('updateLenderAction', id, name, status, trailRate, aliases);

      return { success: true };
    },
  );
```

Here is next-safe-action
```
import { createClient } from '@/supabase/client/server';
import { getUser } from '@/utils/supabase/queries/cached-queries';
import {
 DEFAULT_SERVER_ERROR_MESSAGE,
 createSafeActionClient
} from 'next-safe-action';
import { z } from 'zod';

export class ActionError extends Error {}

export const action = createSafeActionClient({
 handleReturnedServerError: e => {
   console.error('Action server error occurred:', e.message);

   if (e instanceof ActionError) {
     return e.message;
   }
   return DEFAULT_SERVER_ERROR_MESSAGE;
 }
});

export const actionWithMeta = createSafeActionClient({
 handleReturnedServerError(e) {
   if (e instanceof ActionError) {
     return e.message;
   }
   return DEFAULT_SERVER_ERROR_MESSAGE;
 },
 defineMetadataSchema: () => {
   return z.object({
     permission: z.string()
   });
 }
});

export const authAction = actionWithMeta.use(async ({ next, metadata }) => {
 const user = await getUser();
 const supabase = createClient();

 if (!user?.data) {
   throw new ActionError('Unauthorized');
 }

 return next({
   ctx: {
     user: user.data,
     supabase
   }
 });
});

```

### Expected behavior

 Based on the example, this should just work withoout adding `async` 

### Link to a minimal reproduction of the issue

https://github.com/TheEdoRan/next-safe-action/blob/main/apps/playground/src/app/(examples)/with-context/edituser-action.ts#L3

### Operating System

macOS

### Library version

6.2.0

### Next.js version

14.2.3

### Node.js version

20

**Comment by TheEdoRan** [comment]
Hi, I have no issues on my end with that code, and even the [website](https://next-safe-action-playground.vercel.app/with-context) version has no issues. Can you please provide a minimal reproduction example of the issue? Also, I think this is related to #288, which is a Next.js change. Now the library requires callbacks to be async, otherwise the Next project won't build.

**Comment by sagar-jani** [comment]
Thanks @TheEdoRan  - I am still using Next.js 14.  I also looked at the midday-ai open source code and they have the same implementation. 
Here is minimal reproduction example - https://github.com/sagar-jani/safe-action-bug

**Comment by sagar-jani** [comment]
I had upgraded next-safe-action to 7.0.0 and the problem got fixed. 

I use next 14.2.3, is 7.0.0 the latest I can use from next-safe-action ?

**Comment by TheEdoRan** [comment]
Hi @sagar-jani, glad you solved your issue! You should be able to use the latest library version without problems. Let me know if this isn't the case, thanks.

**Comment by calebpdx** [comment]
I had a similar issue.

next 15.2.1
next-safe-action 7.10.4

I had recently updated next, react, react-dom and my Cursor was just mismatching with the update. Restarted my IDE and the error went a away.

**Comment by sagar-jani** [comment]
![Image](https://github.com/user-attachments/assets/38641d39-d33b-4951-9007-5b246a22f87a)

I get this issue again, not sure what's going on ?
