### ISSUE TITLE
PSA: Next.js 15.1 and React 19 are required for next-safe-action >= v7.10.0

### ISSUE THREAD

**Issue by TheEdoRan** [TheEdoRan/next-safe-action#308]
Due to internal framework error handling changes, the minimum required Next.js version is 15.1 and minimum React version is 19. Older framework versions will not work with next-safe-action >= 7.10.0, and vice versa.

**Comment by codeBelt** [comment]
Seems like this is a breaking change. Shouldn't it be `v8.0.0`? It just broke my install.

**Comment by TheEdoRan** [comment]
@codeBelt It's not a breaking change, in my opinion, because library APIs remain the same; nothing has changed. What has changed is the internal error handling mechanism in Next.js, which I unfortunately have no control over. The library APIs are quite stable at this point, though, so you can continue using next-safe-action < 7.10.0 if you don't want to upgrade to Next 15.1. Plan B would have been to include all the new Next.js error handling code in this library, significantly increasing the bundle size and making it quite unmaintainable.

**Comment by lucafaggianelli** [comment]
I also think this should be a breaking change, I updated NSA to 7.10 and it breaks my app as I have Next v14

**Comment by TheEdoRan** [comment]
Hey, thanks to your feedback I realized that releasing a patch version of the library that broke backward compatibility wasn't the brightest idea, even though it didn't directly depend on me or the library APIs, but rather on Next.js ones. I still believe that publishing a new major release isn't necessary if the library APIs remain unchanged.

I've therefore decided to bundle the necessary functions for internal framework error handling related to navigation, allowing support for both older and newer versions of Next.js; these changes are included in stable [v7.10.1](https://github.com/TheEdoRan/next-safe-action/releases/tag/v7.10.1) release. I apologize again for the inconvenience and will do my best to ensure it doesn't happen again in the future.

With the error related functions now integrated into the library code, the system should be more robust, and should also ensure backward compatibility, hopefully.

**Comment by lucafaggianelli** [comment]
ah don't worry you already made an amazing job with Next Safe Action! Ah that's a good solution you released in v7.10.1 thanks!
