### ISSUE TITLE
What's the correct way to iterate the response.validationError?

### ISSUE THREAD

**Issue by lucgagan** [TheEdoRan/next-safe-action#31]
The problem is that key becomes a string, which breaks integration with react-hook-form, which expects one of the predefined keys.

<img width="384" alt="Screenshot 2023-10-22 at 4 29 07 PM" src="https://github.com/TheEdoRan/next-safe-action/assets/134170834/81f0d3bb-8e02-4bb5-b313-a5f0c716a3e3">

**Comment by TheEdoRan** [comment]
You could probably use an utility function like this one:

```typescript
function setFormErrors(form: UseFormReturn<any>, errors: Record<string, string[]>) {
  for (const [field, messages] of Object.entries(errors)) {
    form.setError(field, { message: messages.join(" ") });
  }
}
```

It's not ideal, because you lose type safety (even though it's not really needed in this case). If you find a better way to handle validation errors please let me know. I'll keep this issue open.

**Comment by pazzero** [comment]
For me it worked to destruct the result object like this:
`const { validationError } = result as Record<string, Post>`

Than you can access the validation errors like this:
`{validationError?.title && (
<p className="py-1 text-sm font-bold text-red-500">
{validationError?.title}
</p>
 )}`
