### ISSUE TITLE
[BUG] fix(website):typo-on-create-the-client

### ISSUE THREAD

**Issue by mena0018** [TheEdoRan/next-safe-action#312]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

In the section https://next-safe-action.dev/docs/define-actions/create-the-client#defaultvalidationerrorsshape, there seems to be a discrepancy between the text and the code snippet regarding the default value of defaultValidationErrorsShape.

The text states:
"If this property is not provided, the default shape is formatted, as it also catches errors for nested schema objects."

However, the code snippet mentions:
"By default, all actions will return validation errors in the flattened shape."

This creates confusion about whether the default value is formatted or flattened. Could you clarify which is correct ?

### Reproduction steps

1. Go to : https://next-safe-action.dev/docs/define-actions/create-the-client#defaultvalidationerrorsshape

### Expected behavior

A valid default value

### Link to a minimal reproduction of the issue

 https://next-safe-action.dev/docs/define-actions/create-the-client#defaultvalidationerrorsshape

### Operating System

macOs

### Library version

6

### Next.js version

15

### Node.js version

20

**Comment by TheEdoRan** [comment]
Hi, to me that's pretty clear. The first sentence is in the section description, the second one is in the example code snippet, above the line that's doing the actual thing it refers to.

### Section description

> If this property (`defaultValidationErrorsShape`) is not provided, the default shape is `formatted`, as it also catches errors for nested schema objects.

So, if you don't provide a `defaultValidationErrorsShape` prop to the client init options object, the default shape is `formatted`.

### Code example

> If you instead provide `defaultValidationErrorsShape` to the client and set it to `flattened`, that **will be** the default shape for every action you're going to create.

If you provide the `defaultValidationErrorsShape` prop to the client init options object, that becomes the default shape for all defined actions (that then you can override per action).

Hope this helps!
