### ISSUE TITLE
onSuccess Hook of useAction is not called if action returns undefined

### ISSUE THREAD

**Issue by maltesa** [TheEdoRan/next-safe-action#33]
```ts
// client component
const { execute } = useAction(deleteAssignmentAction, {
  onSuccess: () => {
    console.log('onSuccess was called')
  },
})
```

With this server action:
```ts
export const deleteAssignmentAction = teacherAction(idSchema, async (id, { user }) => {
  // delete assignment ...
  revalidatePath('/assignments')
})
```
The `onSuccess` is not called.
But in this case it is:

```ts
export const deleteAssignmentAction = teacherAction(idSchema, async (id, { user }) => {
  // delete assignment ...
  revalidatePath('/assignments')
  return true
})
```

**Comment by TheEdoRan** [comment]
Yes, this is the expected behavior. You can also return an empty object, instead of `true`. You're required to do that, because `onSuccess` and `onSettled` callbacks get executed if `result.data` isn't undefined.

**Comment by maltesa** [comment]
Hi, thank you for the quick reply. It would be great if that behavior is documented in the docs.

Although, I think that it's unexpected behavior. The absence of data, doesn't mean something was not successful, right? In the example I gave, it just feels unnecessary to return a value.

**Comment by maltesa** [comment]
Awesome. Thanks for the great work. This lib is what I was searching for since I started using server-actions 👍 

Btw. do you plan to extend it for the usage with route.ts files? Kind of a similar pattern.

**Comment by TheEdoRan** [comment]
> do you plan to extend it for the usage with route.ts files? Kind of a similar pattern.

Would be pretty cool, but route handlers implementation is completely different under the hood. It doesn't rely on React's Server Actions feature, so the library would also have to manage fetching, responses, streaming. Maybe one day with `next-safe-route` 👀 . A tiny wrapper that just validates client input with Zod would also be cool.

**Comment by TheEdoRan** [comment]
With this fix, if the action is missing a return statement, `data` will be `null`, and `onSuccess`/`onSettled` callbacks will run after the action finishes executing.
