### ISSUE TITLE
Usage with Form Actions

### ISSUE THREAD

**Issue by xantiagoma** [TheEdoRan/next-safe-action#35]
Hi, thank you for the library.

Is there a way I can use actions directly on `<form action={...}` and `<button formAction={...}`?
Those actions seem to follow `async (prevState: any, formData: FormAction) => ` signature.

What I'm currently doing is to use other function to pass and transform the data

like this:
```typescript
export const login = action(loginFormSchema, async ({ username, password }) => {
  const authRequest = auth.handleRequest("GET", context);
  const key = await auth.useKey("username", username, password);
  const session = await auth.createSession({
    userId: key.userId,
    attributes: {},
  });
  authRequest.setSession(session);
  return;
});

export async function loginFormAction(prevState: any, formData: FormData) {
  "use server";
  const username = formData.get("username") as string;
  const password = formData.get("password") as string;
  const result = await login({ username, password });
  return result;
}

```

I was trying to create a wrapper function.
```typescript
export function toFormAction<
  Schema extends z.ZodTypeAny,
  Data extends any,
  PrevState = any,
>(
  action: SafeAction<Schema, Data>,
): (
  prevState: PrevState,
  formData: FormData,
) => ReturnType<SafeAction<Schema, Data>> {
  return (prevState: PrevState, formData: FormData) => {
    const data = Object.fromEntries(formData.entries());
    return action(data as Data);
  };
}

export const actionFormTheForm = toFormAction(normalAction);
```

Is there an easier built-in approach to these?

**Comment by TheEdoRan** [comment]
You can use the [zod-form-data](https://www.npmjs.com/package/zod-form-data) package as a Zod "adapter" for form data.

In your app you can do something like:

```tsx
// page.tsx
import { signup } from "./signup-action";

export default function SignUpPage() {
  return (
    <form action={signup}>
      <input type="text" name="email" placeholder="name@example.com" />
      <input type="password" name="password" placeholder="••••••••" />
      <button type="submit">Signup</button>
    </form>
  );
}
```

```typescript
// signup-action.ts
"use server";

import { action } from "@/lib/safe-action";
import { zfd } from "zod-form-data";

const schema = zfd.formData({
  email: zfd.text(),
  password: zfd.text(),
});

export const signup = action(schema, async ({ email, password }) => {
  console.log("Email:", email, "Password:", password);
  return {
    success: true,
  };
});
```

[Here's an example](https://github.com/TheEdoRan/next-safe-action/tree/main/packages/example-app/src/app/form). Let me know if this approach solves your issue. Thank you!

**Comment by babycourageous** [comment]
Hi there! Stumbled on this after finding your FormData example on the repo docs. Curious if you wanted to validate/parse the email as a valid email if you would just create two schemas? A zod schema (ie. `z.email()`)  and the form data schema. Then in the signup use zod schema to confirm email (and other more advanced/precise restrictions)

Thanks!

**Comment by TheEdoRan** [comment]
Hey @babycourageous, based on [this example from zod-form-data repo](https://github.com/airjp73/remix-validated-form/tree/main/packages/zod-form-data#usage-1), this should work as expected:

```typescript
const schema = zfd.formData({
  email: zfd.text(z.string().email()),
  password: zfd.text(z.string().min(8)),
});
```

However, I'm not sure if there's a way to access `validationError` using form actions, since they seem much more limited than the ones imported from Client Components. From what I've seen, if the input doesn't pass Zod validation, it silently fails and the action does not execute.
