### ISSUE TITLE
Access input in the middleware

### ISSUE THREAD

**Issue by hdw1219** [TheEdoRan/next-safe-action#36]
Is there a way to access input after zod validation in the middleware?
![Screenshot_206](https://github.com/TheEdoRan/next-safe-action/assets/87274708/939cd220-516b-4f6b-8cef-39122de603d3)

**Comment by TheEdoRan** [comment]
That would be pretty cool and very easy to implement too. The huge problem with this implementation is that input can't be typesafe as a middleware argument, since middlewares are defined per-instance level, while input is action specific. For this reason I'm not sure if it's a good idea to pass input to the middleware as `any`. What do you think?

**Comment by hdw1219** [comment]
Dont take my example for a good solution/suggestion, i added "any" to remove typescript complaining. :) Im really new with TS. As i understand if the input are already validated by zod before middleware is executed, can we add that input type to the middleware params?

**Comment by TheEdoRan** [comment]
>  i added "any" to remove typescript complaining

That's actually the only way I know too to make it work.

> can we add that input type to the middleware params

Types cannot be parameters, but maybe Zod schema could be passed along with action's input (typed `any`).

> For now i check user permissions after the middleware...wich is not useful and not DRY at all :)

Have you already thought about defining multiple action clients to handle this? Or is it not a viable solution in your case?

**Comment by hdw1219** [comment]
in my case the main schema is the same i would pass to the middleware for type validation.

> Have you already thought about defining multiple action clients to handle this? Or is it not a viable solution in your case?

my permissions are so granular that it would be a lot of actions client just to handle this. (well i think...)

**Comment by TheEdoRan** [comment]
Ok, I'll see if I can come up with a good implementation. Thanks for the feedback!
