### ISSUE TITLE
v4 Action statuses change to a single "status" property

### ISSUE THREAD

**Issue by nikitastryuk** [TheEdoRan/next-safe-action#37]
Hey, first of all, huge thanks for this pckg! Good job!

### Problem
 
Quick question/suggestion. What's the background of this change?

<img width="889" alt="image" src="https://github.com/TheEdoRan/next-safe-action/assets/32720808/dcc8eae5-98ca-494e-8a34-7e79c1d2c636">

Single `status` string property is a step back in terms of DX imho. JSX with string conditions (like `status === 'executing'`) looks messier and more code to write. Noticed, I started manually creating `isExecuting` consts (and some for other statuses) all over the project.

### Old api vs New api

```
const { status } = useAction(action);
const isExecuting = status === 'executing';
```
```
const { status, isExecuting } = useAction(action);
```
### Extra

Tanstack Query Api could be great inspiration (for naming things as well) - I assume community got really used to it in past years.

<img width="239" alt="image" src="https://github.com/TheEdoRan/next-safe-action/assets/32720808/282d4517-14a5-4020-a428-e4aef618e1fa">

**Comment by zhouzi** [comment]
I don't know about the actual background of this change but one issue with `hasExecuted`, `isExecuting`, `hasSucceeded` and `hasError` is that they are not discriminating.

From a static analysis standpoint they could be all true at the same time whereas `status` can only be in one state.

**Comment by TheEdoRan** [comment]
> one issue with hasExecuted, isExecuting, hasSucceeded and hasError is that they are not discriminating.

Yes, this is exactly why I changed the API. Also, I think it's way cleaner to have just one `status` key.

> Noticed, I started manually creating isExecuting consts (and some for other statuses) all over the project.

You can define an util function like this:

```typescript
export function isExecuting(status: HookActionStatus): status is "executing" {
  return status === "executing";
}
```

Then import and use it in your Client Components. It's almost the same as having pre-v4 `isExecuting` key, the only difference is that you have to pass the action status to it.

**Comment by TheEdoRan** [comment]
Hope the code snippet above solved your problem. If you have any additional questions about this implementation, feel free to leave a comment here, and, if needed, I'll reopen the issue. Thank you!
