### ISSUE TITLE
feat: initialize an action client with an optional `serverCode` wrapper

### ISSUE THREAD

**Issue by Burry** [TheEdoRan/next-safe-action#39]
Will take a shot at this if I find the time, but I'd love to be able to pass in some function that wraps the server action code when initializing a new server action client. The primary use-case for this is instrumentation and logging the start/end of an action execution, for example [Sentry's new server action utility](https://github.com/getsentry/sentry-javascript/pull/9553). Currently I'm getting around this problem by using middleware to create a wrapping function in context, but first-class support for this feature would be ideal.

**Comment by TheEdoRan** [comment]
That would be pretty cool, we just have to find the best way to implement it. Also, from what I'm seeing, `Sentry.withServerActionInstrumentation()` needs the action name as a key, so it needs to be passed from the action in some way. Any ideas?

**Comment by Burry** [comment]
Maybe we pass the wrapper function a `context` object returned from middleware? That's effectively how I've implemented it. Actually let me clean this up a bit and send something

**Comment by Burry** [comment]
Brain fart, context is per-client. For the action name I wrapped the call to create the client itself with another function that accepted additional params, and created middleware dynamically from that. Kind of jank solution. You could also just use `function.name` for this use case.

**Comment by TheEdoRan** [comment]
Yeah, that's not optimal. I'm not sure there's a good way to implement this without adding first-class support for Sentry in the library. Maybe with a plugin system? Would be pretty complex though, and I really like the simplicity of the codebase. Maybe there's a better solution.

**Comment by ludwigbacklund** [comment]
How about something like this? https://github.com/TheEdoRan/next-safe-action/pull/84

**Comment by TheEdoRan** [comment]
I've just tested Sentry Server Action logging with the new next-safe-action middleware system (currently in `next` branch/channel), and it seems to work as expected. Here's a pretty basic setup, but it can be adapted to your needs:

```typescript
// src/lib/safe-action.ts

import { withServerActionInstrumentation } from "@sentry/nextjs";
import { createSafeActionClient } from "next-safe-action";
import { z } from "zod";
import { headers } from "next/headers";

export const ac = createSafeActionClient({
  defineMetadataSchema() {
    return z.object({
      actionName: z.string(),
    });
  },
}).use(async ({ metadata, next, clientInput, ctx }) => {
  let fd = new FormData();

  if (clientInput instanceof FormData) {
    fd = clientInput;
  } else if (z.object({}).safeParse(clientInput).success) {
    Object.entries(clientInput!).forEach(([k, v]) => {
      fd.append(k, v);
    });
  }

  return await withServerActionInstrumentation(
    metadata?.actionName ?? "unknown action",
    {
      formData: fd,
      headers: headers(),
      recordResponse: true,
    },
    async () => {
      return await next({ ctx });
    }
  );
});
```

You can install the new library version with `npm i next-safe-action@next`. Documentation is currently available [here](https://next.next-safe-action.dev/). If you have any problems, leave a comment here and I'll reopen this issue. Thanks.

**Comment by pangolingo** [comment]
I used @TheEdoRan's [snippet](https://github.com/TheEdoRan/next-safe-action/issues/39#issuecomment-2062387039) to set up Sentry tracking and it worked great. While testing I noticed that it would not log anything to Sentry unless I manually logged the caught error in `handleServerError()`:

```typescript
function isFormDataObject(
  value: unknown,
): value is Record<string, string | Blob> {
  return z
    .record(z.string(), z.union([z.string(), z.instanceof(Blob)]))
    .safeParse(value).success;
}

export const actionClient = createSafeActionClient({
  defineMetadataSchema() {
    return z.object({
      actionName: z.string(),
    });
  },
  handleServerError(e, utils) {
    Sentry.captureException(e);
    return DEFAULT_SERVER_ERROR_MESSAGE;
  },
}).use(async ({ metadata, next, clientInput, ctx }) => {
  let formData = new FormData();

  if (clientInput instanceof FormData) {
    formData = clientInput;
  } else if (isFormDataObject(clientInput)) {
    Object.entries(clientInput).forEach(([k, v]) => {
      formData.append(k, v);
    });
  }

  return withServerActionInstrumentation(
    metadata?.actionName ?? "unknown action",
    {
      formData,
      headers: headers(),
      recordResponse: true,
    },
    async () => {
      return next({ ctx });
    },
  );
});
```

**Comment by kevinmitch14** [comment]
@pangolingo I feel that when applying `withServerActionInstrumentation` you should not need to also use `Sentry.captureException(e)`
