### ISSUE TITLE
Destructure res object in useAction hook

### ISSUE THREAD

**Issue by Xexr** [TheEdoRan/next-safe-action#4]
First, I love this, thank you for sharing.

I've tried both Zact and this and I love that this builds in extensive error reporting, authentication and logging. It makes for a really nice dev experience and brings working with actions close to working with something like React Query. Great stuff.

I have a minor request.

At present the useAction (& useOptimisticAction) hooks return execute, isExecuting, & a res object which has data, serverError, validationError and fetchError.

Because the res object is not always returned, it means you cant directly destructure from res without checking res exists first. No bad thing but I prefer to check the elements under res for existence directly as it results in cleaner code.

Right now, my setup has to look like this:

``` typescript
const { execute, isExecuting, res } = useAction(addTask);
const data = res?.data;
const validationError = res?.validationError;
const serverError = res?.serverError;
const fetchError = res?.fetchError as Error;
```

Whereas I'd greatly prefer if I could do this:

``` typescript
const { execute, isExecuting, data, validationError, serverError, fetchError  } = useAction(addTask);
```

I've built myself a custom hook to be able to do this, but would be cleaner if it was the libraries default behaviour:

``` typescript
// useActionPlus.ts custom hook
import { useAction } from 'next-safe-action/hook';
import type { z } from 'zod';

type ClientAction<IV extends z.ZodTypeAny, AO> = (
  input: z.input<IV>
) => Promise<{
  data?: AO;
  serverError?: true;
  validationError?: Partial<Record<keyof z.input<IV>, string[]>>;
}>;

export const useActionPlus = <const IV extends z.ZodTypeAny, const AO>(
  clientAction: ClientAction<IV, AO>
) => {
  const { execute, isExecuting, res } = useAction(clientAction);
  const data = res?.data;
  const serverError = res?.serverError;
  const validationError = res?.validationError;
  const fetchError: unknown = res?.fetchError;

  return {
    execute,
    isExecuting,
    data,
    serverError,
    validationError,
    fetchError,
  };
};
```

Appreciate your thoughts, perhaps there's an easy solution I'm not thinking of that requires no code change?

**Comment by Xexr** [comment]
I think that sounds great, best of both worlds - thank you.

Perhaps I should raise another issue, but whilst I have you, a couple other queries as I've used it more:

- How are you handling success / failure? e.g. when I call execute, how can I tell if execution succeeded or failed? Can there be an isSuccess res option?
- If there are no error states then that implies success but what I want is something like a callback of onSuccess & onError as parameters in the execute function so that I can take an action once after the mutation runs; or:
- could execute also return the res object (including isSuccess) rather than void so that I can do something like:

``` typescript
<button onClick={() => {
        execute({ id: task.id }).then(({isSuccess, data}) => {
          if (isSuccess) {
            console.log(data.message);
          }
        })
      }}>
```

I believe react query works like this by both returning the key fields from execute and from the useAction hook it means you can react in the moment to success / failure and also access those fields outside the closure easily elsewhere in your component.

**Comment by Xexr** [comment]
I think easier if I demonstrate what I mean. In mocking it up, I've realised that I don't think you can easily return from the execute function as startTransition expects a void return. So I've fallen back to the onSuccess & onError callback functions as an alternative.

The below implements:

- the res destructuring we covered above as per your suggestion
- hasExecuted, isSuccess & onError status fields
- onSuccess & onError callback functions so you can easily specify what happens immediately upon success or failure
- a reset function (also passed to onSuccess & onError) so you can reset state in the hook should you want to

``` typescript
import { useCallback, useEffect, useRef, useState, useTransition } from 'react';
import type { z } from 'zod';

type ClientAction<IV extends z.ZodTypeAny, AO> = (
  input: z.input<IV>
) => Promise<{
  data?: AO;
  serverError?: true;
  validationError?: Partial<Record<keyof z.input<IV>, string[]>>;
}>;

interface UseActionInput<IV extends z.ZodTypeAny, AO> {
  action: ClientAction<IV, AO>;
  onSuccessCb?: (data: AO, reset: () => void) => void;
  onErrorCb?: (
    res: Awaited<ReturnType<ClientAction<IV, AO>>> & { fetchError?: unknown },
    reset: () => void
  ) => void;
}

export const useAction = <const IV extends z.ZodTypeAny, const AO>({
  action,
  onSuccessCb,
  onErrorCb,
}: UseActionInput<IV, AO>) => {
  const [isExecuting, startTransition] = useTransition();
  const executor = useRef(action);
  const onSuccessRef = useRef(onSuccessCb);
  const onErrorRef = useRef(onErrorCb);
  const [res, setRes] = useState<
    Awaited<ReturnType<typeof action>> & { fetchError?: unknown }
  >({});
  const hasExecuted = !!Object.keys(res).length;
  const isSuccess = !!res.data;
  const isError = hasExecuted && !isSuccess;

  const execute = useCallback((input: z.input<IV>) => {
    startTransition(async () => {
      try {
        const res = await executor.current(input);
        setRes(res);
      } catch (e) {
        setRes({ fetchError: e });
      }
    });
  }, []);

  const reset = useCallback(() => {
    setRes({});
  }, []);

  useEffect(() => {
    const onSuccess = onSuccessRef.current;
    if (isSuccess && onSuccess) {
      if (res.data) onSuccess(res.data, reset);
    }
  }, [isSuccess, res.data, reset]);

  useEffect(() => {
    const onError = onErrorRef.current;
    if (isError && onError) {
      if (res) onError(res, reset);
    }
  }, [isError, res, reset]);

  return {
    execute,
    reset,
    isExecuting,
    hasExecuted,
    isSuccess,
    isError,
    res,
  };
};
```

**Comment by TheEdoRan** [comment]
Thank you very much for your code snippets and suggestions. They will greatly improve the DX of this library.
So, I think I implemented all the things you asked for in #5. Please let me know what you think about it!

**Comment by Xexr** [comment]
Oh amazing, thank you!

Looks like you have implemented everything I suggested and super quickly too. I think these are super useful hooks now.

I have one issue but I'm not sure if it's just local to me.

I've cloned the pr, built it, and I'm importing directly from a copy of the dist folder in my current project I'm working on so I can play around with it.

Everything works but one thing... when setting up the action as follows I lose type inference on the resulting execute function

``` typescript
const removeTaskAction = useAction(
    removeTask,
    {
      onSuccess: (data) => {
        console.log(data?.message);
        positionDispatch({ type: 'removeTask' });
      },
      onError: (res) => {
        console.log('Error removing task', res);
      },
    }
  );
```

The signature for it comes through as: `execute: (input: any) => Promise<void>;`

When instead, I specify the types directly for useAction as below, it comes through properly, e.g.:

``` typescript
const removeTaskAction = useAction<RemoveTaskSchema, ActionResponse>(
    removeTask,
    {
      onSuccess: (data) => {
        console.log(data?.message);
        positionDispatch({ type: 'removeTask' });
      },
      onError: (res) => {
        console.log('Error removing task', res);
      },
    }
  );
```

The signature now looks like this: `execute: (input: {
        id: number;
    }) => Promise<void>;`

However, when I used the previous version of useAction, it inferred the types correctly without me specifying. Is this a bug or some issue with my setup?

**Comment by Xexr** [comment]
Ah, figured it out.

Silly user error, I hadn't updated createSafeActionClient to import from my standalone folder, so I guess the types were all messed up.

Good to go! 😀

**Comment by TheEdoRan** [comment]
Ok, let me update the README, then I'll merge the PR and release the new version.
