### ISSUE TITLE
Feature Request: better pattern for using actions with intellisense

### ISSUE THREAD

**Issue by Apestein** [TheEdoRan/next-safe-action#40]
I really enjoy this pattern from create-t3-app with trpc:
```ts
import { api } from "~/trpc/server";
const hello = await api.post.hello.query({ text: "from tRPC" }); //example from create-t3-app boilerplate 
```
It would be nice to have an api/actions object with all actions in it for easy access with intellisense. Something like this:
```ts
import { nsa } from "~/nsa/actions";
const foo = await nsa.post.createPost({...})
```
https://create.t3.gg/

**Comment by TheEdoRan** [comment]
Something like this works:

```typescript
const createAction = createSafeActionClient();

const actions = {
  post: {
    create: createAction(
      z.object({ title: z.string(), body: z.string() }),
      async ({ body, title }) => {
        return {
          success: true,
        };
      }
    ),
  },
};
```

Or this, if you want to use different files for your "routers":

```typescript
const post = {
  create: createAction(
    z.object({ title: z.string(), body: z.string() }),
    async ({ body, title }) => {
      return {
        success: true,
      };
    }
  ),
};

const actions = {
  post,
};
```

And then:
```typescript
actions.post.create({ title: "test", body: "123" });
```

**Comment by Apestein** [comment]
> Something like this works:
> 
> ```ts
> const createAction = createSafeActionClient();
> 
> const actions = {
>   post: {
>     create: createAction(
>       z.object({ title: z.string(), body: z.string() }),
>       async ({ body, title }) => {
>         return {
>           success: true,
>         };
>       }
>     ),
>   },
> };
> ```
> 
> Or this, if you want to use different files for your "routers":
> 
> ```ts
> const post = {
>   create: createAction(
>     z.object({ title: z.string(), body: z.string() }),
>     async ({ body, title }) => {
>       return {
>         success: true,
>       };
>     }
>   ),
> };
> 
> const actions = {
>   post,
> };
> ```
> 
> And then:
> 
> ```ts
> actions.post.create({ title: "test", body: "123" });
> ```

Thanks, idk why I didn't think of this🤦‍♂️
