### ISSUE TITLE
Import of "next/dist/client/components/not-found" fails in "next-safe-action/dist/index.mjs" with ES Modules

### ISSUE THREAD

**Issue by lean1190** [TheEdoRan/next-safe-action#42]
### Problem

I'm currently working on a project with Nextjs 14.0.4, Next Safe Action 5.2.1, and Vitest 1.0.4.
The problem I am facing is that when I run Vitest on a file that imports Next Safe Action, the tests fail with the following error:

<img width="1388" alt="Screenshot 2023-12-17 at 18 41 04" src="https://github.com/TheEdoRan/next-safe-action/assets/10180988/f0c73a0f-2634-4a3a-8722-cb8052e2a033">

My understanding is that Vitest 1.0.4 is now running on Vite 5, which uses ES Modules by default. 
This also means that, and please correct me if I’m wrong, ES Modules need to import CommonJs modules by adding the file extension. Since the Next Safe Action library is exported in the `index.mjs` and `hook.mjs` files as ES Modules, they should import the dependencies with the file extensions.

### What I tried to solve the problem

I did the simplest thing I could try, I went to `/node_modules/next-safe-action/dist/index.mjs` and added the file extension to the imports, as:

```jsx
// src/server.ts
import { isNotFoundError } from "next/dist/client/components/not-found.js";
import { isRedirectError } from "next/dist/client/components/redirect.js";
```

This solved the problem, although is not a permanent solution.

### Suggestion

We add the file extensions to the imports in `src/server.ts` and `src/hook.ts`

**Comment by lean1190** [comment]
I also want to take the chance to say thanks for building this amazing library, it simplifies so many things that would be much more complicated to deal with otherwise, and it’s been a must for me since I started working with Nextjs ❤️

**Comment by TheEdoRan** [comment]
Thank you for your kind words. next-safe-action uses tsup for builds, which uses esbuild under the hood. I haven't found a way to make it work automagically, so I manually added ".js" to imported files in order to make it work. Please let me know if v5.2.3 fixes the issue, thank you!

**Comment by lean1190** [comment]
Thank you so much for the prompt response, I've just tested the new version, and it's working as expected 🙌
