### ISSUE TITLE
When using `useAction()` can you directly import the server action in the client component or do you pass it down from a server component?

### ISSUE THREAD

**Issue by Lermatroid** [TheEdoRan/next-safe-action#43]
In the docs on [this page](https://next-safe-action.dev/docs/usage-from-client/hooks/useaction) it seems as if the function is being directly being imported from the file it is defined in, however other sections of the docs discuss passing it down through the server function. 

Which is the correct way to go about this? Thanks!

**Comment by TheEdoRan** [comment]
> other sections of the docs discuss passing it down through the server function

Are you referring to old READMEs? I thought I updated all sections of the new documentation with the correct information. Please let me know if this isn't the case, thank you!

You can _almost always_ directly import server actions in Client Components, there are a few cases when this doesn't work properly, I discussed the behavior in #25. So, if you experience some weird revalidation bugs, you should instead pass them as props from Server Components.

**Comment by TheEdoRan** [comment]
I'm closing this issue for now. If something is still unclear, please leave a comment here and I'll reopen the issue. Thank you!
