### ISSUE TITLE
[BUG] Package is incompatible with Vitest

### ISSUE THREAD

**Issue by ludwigbacklund** [TheEdoRan/next-safe-action#54]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

Importing anything from `next-safe-action/hooks` causes Vitest tests to crash due to how React is being imported in that file.
I don't fully understand how the module resolution works here so I cannot tell you exactly why this happens, but I do know that making the following change in the `hooks.mjs` file fixes the problem 👇 

```
diff --git a/dist/hooks.mjs b/dist/hooks.mjs
index 636b65d50449fa41e913bb5bb632370f8f4f9df9..7f48d3c48278d76c36a73ae6bf99bed51ba5679b 100644
--- a/dist/hooks.mjs
+++ b/dist/hooks.mjs
@@ -3,7 +3,8 @@
 // src/hooks.ts
 import { isNotFoundError } from "next/dist/client/components/not-found.js";
 import { isRedirectError } from "next/dist/client/components/redirect.js";
-import { useCallback, useEffect, useOptimistic, useRef, useState, useTransition } from "react";
+import pkg from 'react';
+const { useCallback, useEffect, useOptimistic, useRef, useState, useTransition } = pkg;
```

That's a patch I've applied temporarily to fix the issue in my project.

### Reproduction steps

1. Open https://stackblitz.com/edit/vitest-dev-vitest-6lgc1a?file=test%2Fbasic.test.tsx
2. See test fail
3. Comment out the 'next-safe-action/hooks' import and the useAction invocation further down
4. See test pass

### Expected behavior

The test should pass without failing due to how React is being imported.

### Reproduction example

https://stackblitz.com/edit/vitest-dev-vitest-6lgc1a?file=test%2Fbasic.test.tsx

### Operating System

macOS

### Library version

6.0.1

**Comment by TheEdoRan** [comment]
Hi @ludwigbacklund, thanks for opening this issue. I switched from React hooks named imports to a namespace import in the new beta version, that you can install it with: 

```sh
npm i next-safe-action@beta
```

This should fix the problem with Vitest. Please let me know if everything works fine with the new release, if that's the case, I'll publish a new version in the stable channel soon. Thank you!

**Comment by ludwigbacklund** [comment]
@TheEdoRan Thanks! It works 👍
