### ISSUE TITLE
[FEATURE] Allow for actions with no validators (no parameters)

### ISSUE THREAD

**Issue by dBianchii** [TheEdoRan/next-safe-action#59]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Suggest an idea

I'd like to be able to use next-safe-action without needing to pass any schema as an input to the first parameter. This could be accomplished by send `undefined` as the first parameter.

![image](https://github.com/TheEdoRan/next-safe-action/assets/17372417/fe736a60-7411-425c-832c-be36794ec930)

### Additional context

If maintainers of this repo think this would be a good idea, I would like to try to work on this one.

Thank you!

**Comment by TheEdoRan** [comment]
You can pass `z.void()` as schema, assuming you're using Zod for validation. Check out [the comment I left in this issue](https://github.com/TheEdoRan/next-safe-action/issues/23#issuecomment-1843950045). Please let me know if this fixes your problem, thank you!

**Comment by dBianchii** [comment]
> You can pass `z.void()` as schema, assuming you're using Zod for validation. Check out [the comment I left in this issue](https://github.com/TheEdoRan/next-safe-action/issues/23#issuecomment-1843950045). Please let me know if this fixes your problem, thank you!

Thank you! It worked perfectly! Didn't know this existed
