### ISSUE TITLE
Consistent `types.ts` Filename

### ISSUE THREAD

**Issue by destruc7i0n** [TheEdoRan/next-safe-action#6]
I have been reusing the types in `types.ts` in my project and noticed that each minor version the `types.ts` file has its name change with a hash: 

* 2.6.3: [types-b1af0f6d.d.ts](https://unpkg.com/browse/next-safe-action@2.6.3/types-b1af0f6d.d.ts)
* 2.5.6: [types-ed8c61f6.d.ts](https://unpkg.com/browse/next-safe-action@2.5.6/types-ed8c61f6.d.ts)

Is there a specific design reason behind these name changes? If not, would it be possible to maintain a consistent filename or export the types?

**Comment by TheEdoRan** [comment]
The hashing is done automatically by tsup, don't know if it's configurable, but I think that the best option would be to export types from the package. I'll publish a new version with exported types today. Thank you for opening this issue!
