### ISSUE TITLE
[BUG] - NextJs passing additional arguments to server form action .bind(null, userId) is not working

### ISSUE THREAD

**Issue by tiavina-mika** [TheEdoRan/next-safe-action#60]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

I want to pass additional arguments as the NextJs doc [said](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#binding-arguments)
, mainly for edition while a I need an `id` along with the` form values`.

```javascript
// form.tsx
'use client'
 
import { updateUser } from './actions'
 
export function UserProfile({ userId }: { userId: string }) {
  const updateUserWithId = updateUser.bind(null, userId)
 
  return (
    <form action={updateUserWithId}>
      <input type="text" name="name" />
      <button type="submit">Update User Name</button>
    </form>
  )
}
```

```javascript
// server actions
'use server'
 
import { SafeAction } from 'next-safe-action';

export const updateUser = async action(UserSchema, (userId, formData) => {
  // ...
})

```

### Reproduction steps

use the exemple in the [Next doc](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#binding-arguments) 

### Expected behavior

The update should be working and the data saved

### Reproduction example

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#binding-arguments

### Operating System

Windows 10

### Library version

6.0.2

**Comment by TheEdoRan** [comment]
This is a feature, not a bug, since Form Actions are a subset of React Server Actions with a slightly different behavior and function signature. That said, #29 is still open and I'm going to provide updates on the implementation there.
