### ISSUE TITLE
[FEATURE]  Add isSuccess, isLoading etc to useAction return object

### ISSUE THREAD

**Issue by John-Dennehy** [TheEdoRan/next-safe-action#61]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Suggest an idea

While `status` already exists, I find myself needing to creating the same additional "boiler-plate" code around the status string value every time I use useAction; specifically creating boolean variables such as `isLoading` for button state.

While not a high priority, it would be nice if the response object was a more similar to projects like tanstack/react-query that include both the `status` string **and** boolean variables like: 

- isLoading
- isSuccess
- isError

I imagine any accepted change would need to be applied to useOptimisticAction too.

**Comment by John-Dennehy** [comment]
FYI - I'd be happy to raise a PR if there is an appetite for this.

**Comment by TheEdoRan** [comment]
Hi @John-Dennehy, next-safe-action v3 actually returned an object with `hasExecuted`, `isExecuting`, `hasSucceeded` and `hasErrored` properties, this changed in v4, you can read about it in the [v3 to v4 migration guide](https://next-safe-action.dev/docs/migration-from-v3-to-v4#hooks) on the website.

This specific change has been already discussed in [this issue](https://github.com/TheEdoRan/next-safe-action/issues/37), and in [this comment](https://github.com/TheEdoRan/next-safe-action/issues/37#issuecomment-1817505879) I explained why I made it and a possible solution to avoid repeating code, defining simple util functions for the scope.

Please let me know if there's anything else I can help you with, thank you.

**Comment by John-Dennehy** [comment]
Sorry for missing that.  That is a shame really.

**Comment by TheEdoRan** [comment]
No worries! By the way, we could export those utility functions from the library itself, but I'm not sure if this is the right thing to do, not everybody will use them, and defining them in one place is quite simple already. What do you think?

**Comment by TheEdoRan** [comment]
Action status utility functions implemented in `6.1.0` release. Relevant documentation can be found [here](https://next-safe-action.dev/docs/usage-from-client/hooks/checking-action-status).
