### ISSUE TITLE
A "use server" file can only export async functions issue

### ISSUE THREAD

**Issue by GorkemEldeniz** [TheEdoRan/next-safe-action#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Library version (optional)

6.1.0

### Ask a question

After exporting my safe action objects, I get the following error, which I did not get when doing the same operation in older versions
_A "use server" file can only export async functions, found object._

## createSafeActionClient 
![image](https://github.com/TheEdoRan/next-safe-action/assets/82877261/9f75e82a-1955-4e17-b654-c7dddbf76b41)

## My Custom Safe Action
![safe-action](https://github.com/TheEdoRan/next-safe-action/assets/82877261/2dd628fb-843e-4c79-9413-3f7e51535600)

**Comment by GorkemEldeniz** [comment]
Unnecessary uploadSchema object is exported that's why next throws an error

**Comment by kiranavaibe** [comment]
https://nextjs.org/docs/messages/invalid-use-server-value

export const signIn = action(signInSchema, async ({username, password}) => {
  try {
    const res = await fetch('http://localhost:8080/api/v1/users/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        username,
        password
      })
    });
    const data = await res.json();
    if(data?.data) {
      await handleLogin(data.data.userId, data.data.accessToken, data.data.refreshToken)
    }
    return new ResponseBody("Login Successful", false, data.data)
  } catch (error) {
    return { failure: 'Login failed' };
  }
});

A "use server" file can only export async functions, found object. Still getting the fetch error
