### ISSUE TITLE
i there a way to use the action wrapper without input validation

### ISSUE THREAD

**Issue by AlaaMX** [TheEdoRan/next-safe-action#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Ask a question

Hello, i wanted to ask if there is a way to use the createSafeActionClient wrapper without input validation and still getting all the status right ?

**Comment by TheEdoRan** [comment]
Hi @AlaaMX, do you mean creating actions without input data?

**Comment by AlaaMX** [comment]
Exactly @TheEdoRan .

**Comment by TheEdoRan** [comment]
Check out issue #59 and [this comment](https://github.com/TheEdoRan/next-safe-action/issues/23#issuecomment-1843950045).
