### ISSUE TITLE
Pass parameter to middleware serverside? [ASK] 

### ISSUE THREAD

**Issue by SimtecConsult** [TheEdoRan/next-safe-action#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Ask a question

Is there a way to pass a variable to the middleware server side?

I want to setup some middleware that checks if a user has permission to perform an action. To do this I would like to be able to pass a value to the middleware (the permission the user requires), that the middleware can then check before performing the action.

I already have a function that takes the permission required as an input, and returns true or false depending on the user, but I see no way to pass this string to the middleware anywhere. 

I could do it in the form, but this would leave it open to manipulation.

Currently I've just copy/pasted the action client for each permission, passing a different string for each.

**Comment by TheEdoRan** [comment]
Hey @SimtecConsult, are you requesting the same thing #67 wants to implement? I.e. passing a "static" value per-action, outside of the action server code function body? Am I understanding your request correctly?

**Comment by SimtecConsult** [comment]
@TheEdoRan  Yes this is exactly what I'm after.
