### ISSUE TITLE
[ASK] Optimistic update error handling

### ISSUE THREAD

**Issue by Chunkygoo** [TheEdoRan/next-safe-action#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Ask a question

How can I rollback to the previous state if I optimistically update data but the actual API call fails? In React Query, there's an onError and in there I can simply rollback to the previous state. See https://create.t3.gg/en/usage/trpc#optimistic-updates

**Comment by TheEdoRan** [comment]
With my tests using `useOptimisticAction` hook, if an error occurs during the server code function execution, the `optimisticData` correctly rolls back to the previous value. Can you please provide a link to a repo with a minimal reproduction of the issue? Thanks.

**Comment by Chunkygoo** [comment]
Hey, sorry if I wasn't clear before. I was asking for a way to rollback. Is there a tutorial that shows how this is done?

**Comment by TheEdoRan** [comment]
> I was asking for a way to rollback

I thought I understood your question. What I'm saying is that `useOptimistic` hook from React, which `useOptimisticAction` uses under the hood, automatically handles rollback to the previous value if an error occurs during action execution. Isn't that what you want?
