### ISSUE TITLE
Safe Actions on Edge

### ISSUE THREAD

**Issue by Lermatroid** [TheEdoRan/next-safe-action#9]
Is there a way to run safe actions on edge? I know with API routes and pages its:

```ts
export const runtime = "edge"
```

But I am not sure how to go about this with the library. Thanks for the help!

**Comment by TheEdoRan** [comment]
Hi, thanks for opening this issue. I personally haven't tested the runtime behavior, but this library is simply a typesafe wrapper around Next.js Server Actions, so it feels like a Next.js issue rather than a lib one. Check out vercel/next.js/discussions/49605 for more details.

**Comment by TheEdoRan** [comment]
Closing the issue for now. If you need any additional help regarding this (assuming this is a lib problem), feel free to leave a comment and I'll reopen it. Thank you!
