### ISSUE TITLE
[BUG] [V7] TypeScript error when action clients are exported with "declaration: true" is set in tsconfig 

### ISSUE THREAD

**Issue by ludwigbacklund** [TheEdoRan/next-safe-action#95]
### Are you using the latest version of this library?

- [X] I verified that the issue exists in the latest next-safe-action release

### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing that matches

### Describe the bug

When running next-safe-action v7 in a TypeScript project with "declaration: true" set in tsconfig.json, a TypeScript error occurs as soon as you try to export a created action client.

```ts
import { createSafeActionClient } from 'next-safe-action';

/** 
Property '_metadata' of exported class expression may not be private or protected.ts(4094)
Property 'handleReturnedServerError' of exported class expression may not be private or protected.ts(4094)
Property 'handleServerErrorLog' of exported class expression may not be private or protected.ts(4094)
Property 'middlewareFns' of exported class expression may not be private or protected.ts(4094) 
*/
export const actionClient = createSafeActionClient();
```

### Reproduction steps

1. Create a TypeScript/Next.js project with "declaration: true" in tsconfig.json
2. Create an action client with `createSafeActionClient`
3. Export it

### Expected behavior

It should not error

### Reproduction example

https://stackblitz.com/edit/stackblitz-starters-mvsrjh?file=app%2Faction-client.ts

### Operating System

Ubuntu

### Library version

7.0.0-next.14

**Comment by TheEdoRan** [comment]
Please let me know if #96 fixed your issue, thanks!

**Comment by ludwigbacklund** [comment]
Works great 👍
